### PR TITLE
pop3d: try to not split ".\r\n" across packet boundary

### PR DESCRIPTION
**Pull request by elliefm**
Works around some Thunderbird bug.  Based on patch provided and tested in #4717 by @yaonos

Fixes: #4717

### CODE REVIEW

**Review by ksmurchison — COMMENTED** [review]
Not sure I understand why a flush before and after is needed

**Comment by elliefm** [comment]
As I understand it, the problem occurs when the protstream's buffer was already within a byte or two of a packet boundary, such that when the ".\r\n" sequence is written, part of it is at the end of one packet and the rest is at the start of the next.  Apparently Thunderbird gets confused when that specific sequence is split up.

I think the first flush causes whatever was already in the buffer to be sent as is, rather than waiting for more bytes to fill out the packet.  Then the ".\r\n" becomes the start of the next packet, and stays intact.  The unconditional flush probably results in more packets than strictly necessary, which might be preventable by examining the pending buffer length, knowing the packet size, and only flushing if it were actually necessary to prevent a split.  But I don't think anyone wants to write and test that, and this works.

I suspect the second flush might be redundant, but it was in the patch that OP provided and tested, so it's in mine too.

**Comment by yaonos** [comment]
The second flush may Indeed bé redundant.
As explained by @elliefm the goal of the first flush is to avoid spliting ".\r\n" on 2 packets.
Regards

**Comment by ksmurchison** [comment]
Yes, I believe it is redundant since flushonread has been set on the input stream and we iterate back to the top of cmdloop() as soon as we exit blat()

**Comment by elliefm** [comment]
Since we all agree it's probably redundant, I've dropped the second flush

**Review by ksmurchison — APPROVED** [review]

**Pull request merged**
