### PR TITLE
Create no intermediates

### PR DESCRIPTION
**Pull request by ksmurchison**
Relevant Cass changes are here: https://github.com/cyrusimap/cassandane/pull/111

### CODE REVIEW

**Review by brong — APPROVED** [review]
Yep, that looks sensible

**Comment by ksmurchison** [comment]
@brong Did you also look at the Cass PR?

**Comment by ksmurchison** [comment]
Oh, and do we want this gated by a config option or no?

**Comment by brong** [comment]
No let's just make it this.  Intermediates suck.

**Comment by ksmurchison** [comment]
@brong Am incorrect that INBOX.INBOX needs to stay as an intermediate?

**Comment by brong** [comment]
INBOX.INBOX needs to not exist at all - no intermediate required.  It should be an actual blank space in the tree.

**Pull request merged**
