### PR TITLE
Handle Google iTIP Replies

### PR DESCRIPTION
**Pull request by ksmurchison**
Google sends iTIP replies for RECURRENCE-IDs in UTC, even if DTSTART has a TZID.
This PR supports these replies by normalizing R-IDs to UTC for comparison and adjusts new R-IDs to the TZID of DTSTART.

### CODE REVIEW

**Review by rsto — CHANGES_REQUESTED** [review]
The solution approach looks good to me, but this branch repeatedly fails Cassandane tests on my build. The tests succeed on the master branch.

Running these suites:

```+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty JMAPBackup
+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty JMAPCalendars
+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty JMAPContacts
+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty JMAPCore
+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty JMAPEmail
+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty JMAPEmailSubmission
+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty JMAPMailbox
+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty JMAPSieve
+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty FastMail
+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty Caldav
+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty CaldavAlarm
+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty Carddav
+ sudo -u cyrus ./testrunner.pl -j 7 -f pretty JMAPTestSuite
```

I get

```Cyrus::JMAPBackup.restore_calendars_all_dryrun                          [FAILED]
Cyrus::JMAPBackup.restore_calendars_all                                 [FAILED]
Cyrus::JMAPCalendars.calendar_changes                                   [FAILED]
Cyrus::JMAPCalendars.calendar_set                                       [FAILED]
Cyrus::JMAPCalendars.calendar_set_destroy_events                        [FAILED]
Cyrus::JMAPCalendars.calendar_set_destroyspecials                       [FAILED]
Cyrus::JMAPCalendars.calendar_set_error                                 [FAILED]
Cyrus::JMAPCalendars.calendar_set_shared                                [FAILED]
Cyrus::JMAPCalendars.calendar_set_state                                 [FAILED]
Cyrus::JMAPCalendars.calendarevent_query_deleted_calendar               [ERROR ]
Cyrus::JMAPCalendars.calendarpreferences_defaultcalendar                [FAILED]
Cyrus::Caldav.replication_delete                                        [ERROR ]
Cyrus::JMAPTestSuite.t:core:upload                                      [FAILED]
```

**Comment by ksmurchison** [comment]
@rsto Please test again.  I reverted a previous bad iTIP related commit and now all of the tests pass for me

**Comment by rsto** [comment]
They pass, but the `Sieve.imip_reply_override_google` test has valgrind errors.

**Comment by ksmurchison** [comment]
@rsto Use of freed memory issue fixed

**Review by rsto — APPROVED** [review]
LGTM

**Pull request merged**
