### PR TITLE
Remove support for DAV:displayname on JMAP Mailboxes

### PR DESCRIPTION
**Pull request by ksmurchison**

### CODE REVIEW

**Review by rsto — APPROVED** [review]
Looks good to me. There is the slight risk that some mailboxes were created during the time where Cyrus allowed to duplicate names, which would have IMAP mailbox names like mailbox and mailbox1. If keeping the read part of the displayname annotation is worth it to prevent that, I don't know.

**Comment by ksmurchison** [comment]
If we keep the read part, what do we do for a mailbox rename?  That's what brought this to our attention.  If we can solve the mailbox rename issue, we can keep the annotation, but so far trying to delete/rename the annotation has been causing other issues

**Comment by rsto** [comment]
Right, so in that case I'd say it's not worth the effort to keep that annotation. I don't even think we ever released a stable Cyrus that included the support for duplicate names.

**Comment by ksmurchison** [comment]
If we never released it then I think we're safe with this.

**Comment by rsto** [comment]
Agreed

**Pull request merged**
