### PR TITLE
squatter: further clarifications (3.0)

### PR DESCRIPTION
**Pull request by dilyanpalauzov**

### CODE REVIEW

**Comment by elliefm** [comment]
Sorry, I finally backported the rsync/rm fixes and now this PR is conflicting :(

**Comment by dilyanpalauzov** [comment]
Please propose how to proceed.

**Comment by elliefm** [comment]
I'm gonna try to use the "Resolve conflicts" button on the github web UI to fix it up... I tried to do this yesterday but gave up after about half an hour of it not loading up (probably slow internet my side?)

**Comment by ksmurchison** [comment]
Similar changes exists on master and we no longer support 3.0.x.

**Comment by dilyanpalauzov** [comment]
https://github.com/cyrusimap/cyrus-imapd/pull/2779 applied very similar changes to the (then) master branch. At the time this was submitted, five years ago, the 3.0 branch was supported.

**Pull request closed without merging**
