### PR TITLE
More vCard v3 <-> v4 translations

### PR DESCRIPTION
**Pull request by ksmurchison**
This PR will fail CI until we update to the latest libical vCard branch

### CODE REVIEW

**Comment by rsto** [comment]
The `vcard` branch doesn't merge cleanly with `libical/master`, so we need to sort out these conflicts first.

**Review by rsto — CHANGES_REQUESTED** [review]
The `vcard` branch doesn't merge cleanly with `libical/master`, so we need to sort out these conflicts first.

**Comment by ksmurchison** [comment]
> The `vcard` branch doesn't merge cleanly with `libical/master`, so we need to sort out these conflicts first.

This has been fixed.

**Comment by rsto** [comment]
@ksmurchison I'm not on top of this here anymore. Is CI failing because it requires new cyruslibs? But Github CI doesn't make use of libicalvcard anyway.

**Comment by ksmurchison** [comment]
@rsto I was able to fix the vparse side of things so that CI passes.

**Review by rsto — APPROVED** [review]

**Pull request merged**
