### PR TITLE
Make some variables static

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
as suggested by clang -Wmissing-variable-declarations

### CODE REVIEW

**Comment by rsto** [comment]
Would you still want to get this merged? If so, would you rebase to latest master and return with `-Wmissing-variable-declarations`?

**Comment by rsto** [comment]
@elliefm what's your take on this?

**Comment by elliefm** [comment]
These changes all seem reasonable.  I'll pull the branch and resolve the conflicts locally, see what I think, and if it's still good I'll merge it manually.

**Review by elliefm — APPROVED** [review]

**Comment by elliefm** [comment]
Manually merged as d95bd0b33

**Comment by dilyanpalauzov** [comment]
QSTRINGCHAR moved from jmap_mail.c to charset.c, but it should still be static.

**Pull request closed without merging**
