### PR TITLE
make 'check' etc fail on cunit valgrind errors

### PR DESCRIPTION
**Pull request by elliefm**
This makes it so that cunit-under-valgrind will fail if valgrind detects memory errors, instead of reporting the valgrind errors to the terminal but still succeeding.  This will be more useful for automated testing.
    
Specifically, this affects the following make targets:
* check
* check-local
* check-%
    
The check-discrete make target already behaved like this, and is no longer a special case.

Also fixes a few memory leaks that had snuck into our unit tests since last time I looked at them.

**Reviewers**: to test this, run `make VG=1 check` after introducing a memory leak somewhere (such as by temporarily reverting one of the testc fixes on this branch).  Expect `echo $?` to be non-zero afterwards.  For comparison, the same on the master branch would report the leak, but `echo $?` would be zero.

### CODE REVIEW

**Review by rsto — COMMENTED** [review]
The `parse` test suite fails for some tests with errors such as 

      Test: getint32 ...**430717** fatal(num too big)
    ==430717==    at 0x13D554: VALGRIND_PRINTF_BACKTRACE (valgrind.h:6807)
    ==430717==    by 0x13EA1B: fatal (unit.c:100)
    ==430717==    by 0x491451B: getint32 (imapparse.c:272)
    ==430717==    by 0x21EC9F: test_getint32 (parse.testc:121)
    ==430717==    by 0x13EB4B: __cunit_wrap_test (unit.c:166)
    ==430717==    by 0x21B417: __cunit_test_getint32 (parse.testc-cunit.c:19)
    ==430717==    by 0x4F7C487: ??? (in /usr/lib/aarch64-linux-gnu/libcunit.so.1.0.1)
    ==430717==    by 0x4F7C723: ??? (in /usr/lib/aarch64-linux-gnu/libcunit.so.1.0.1)
    ==430717==    by 0x4F7CB67: CU_run_all_tests (in /usr/lib/aarch64-linux-gnu/libcunit.so.1.0.1)
    ==430717==    by 0x13E647: run_tests (unit.c:356)
    ==430717==    by 0x13F1C3: main (unit.c:482)
    passed

Do you see these, too? Maybe that's due to me building this in on an ARM CPU: `aarch64-linux-gnu`

**Comment by rsto** [comment]
Actually, that test is expected to fail fatally. But I get a valgrind error:

    $ make VG=1 check
    $ echo $?
    2

There's also Valgrind errors such as

      Test: sasl_digestmd5 ...==431798==
    ==431798== Process terminating with default action of signal 15 (SIGTERM)
    ==431798==    at 0x51230AC: accept (accept.c:26)
    ==431798==    by 0x16C973: server_accept (backend.testc:901)
    ==431798==    by 0x16DA23: server_start (backend.testc:1379)
    ==431798==    by 0x16DB87: set_up (backend.testc:1612)
    ==431798==    by 0x13EC23: __cunit_wrap_fixture (unit.c:181)
    ==431798==    by 0x16AAAF: __cunit_test_sasl_digestmd5 (backend.testc-cunit.c:58)
    ==431798==    by 0x4F7C487: ??? (in /usr/lib/aarch64-linux-gnu/libcunit.so.1.0.1)
    ==431798==    by 0x4F7C723: ??? (in /usr/lib/aarch64-linux-gnu/libcunit.so.1.0.1)
    ==431798==    by 0x4F7CB67: CU_run_all_tests (in /usr/lib/aarch64-linux-gnu/libcunit.so.1.0.1)
    ==431798==    by 0x13E647: run_tests (unit.c:356)
    ==431798==    by 0x13F1C3: main (unit.c:482)
    ==431798==
    ==431798== HEAP SUMMARY:
    ==431798==     in use at exit: 75,780 bytes in 1,712 blocks
    ==431798==   total heap usage: 532,459 allocs, 530,747 frees, 91,264,075 bytes allocated
    ==431798==
    ==431798== LEAK SUMMARY:
    ==431798==    definitely lost: 0 bytes in 0 blocks
    ==431798==    indirectly lost: 0 bytes in 0 blocks
    ==431798==      possibly lost: 0 bytes in 0 blocks
    ==431798==    still reachable: 75,780 bytes in 1,712 blocks
    ==431798==         suppressed: 0 bytes in 0 blocks
    ==431798== Reachable blocks (those to which a pointer was found) are not shown.
    ==431798== To see them, rerun with: --leak-check=full --show-leak-kinds=all

Do you see these too?

**Comment by rsto** [comment]
I now found the offending valgrind issue

    ==80587== Syscall param epoll_ctl(event) points to uninitialised byte(s)
    ==80587==    at 0x5122A88: epoll_ctl (syscall-template.S:120)
    ==80587==    by 0x889C64B: ??? (in /usr/lib/aarch64-linux-gnu/libnss_systemd.so.2)
    ==80587==    by 0x889CA8B: ??? (in /usr/lib/aarch64-linux-gnu/libnss_systemd.so.2)
    ==80587==    by 0x888505B: _nss_systemd_getpwnam_r (in /usr/lib/aarch64-linux-gnu/libnss_systemd.so.2)
    ==80587==    by 0x50F2E63: getpwnam_r@@GLIBC_2.17 (getXXbyYY_r.c:315)
    ==80587==    by 0x50F27DF: getpwnam (getXXbyYY.c:135)
    ==80587==    by 0x4B088BF: mynewstate (auth_unix.c:229)
    ==80587==    by 0x4B0738B: auth_newstate (auth.c:104)
    ==80587==    by 0x15A57F: set_up (annotate.testc:2206)
    ==80587==    by 0x13EC23: __cunit_wrap_fixture (unit.c:181)
    ==80587==    by 0x159BE3: __cunit_test_getset_server_shared (annotate.testc-cunit.c:9)
    ==80587==    by 0x4F7C487: ??? (in /usr/lib/aarch64-linux-gnu/libcunit.so.1.0.1)
    ==80587==  Address 0x1ffefff3ac is on thread 1's stack

I vaguely recall that I had to suppress these earlier, so I guess that now indeed is an architecture/libc issue. There's a bunch of similar issues.

I am now going to approve this PR since it works as intended, it just surfaced issues on my build platform.

**Review by rsto — APPROVED** [review]

**Comment by elliefm** [comment]
@rsto,

> ==80587== Syscall param epoll_ctl(event) points to uninitialised byte(s)
> [...]
> ==80587==  Address 0x1ffefff3ac is on thread 1's stack

Oh, that's interesting.  I wonder if our cunit infrastructure (or annotate.testc specifically) is doing something sketchy, but which only gets complained about on ARM...

If you investigate this and determine that it's not a real problem, the place to add a suppression for it is `cunit/vg.supp`.

I notice our cassandane suppressions file (`cassandane/vg.supp`) already has a suppression for `epoll_ctl()` for non-amd64 64bit, though at glance it doesn't look like the same issue.

**Pull request merged**
