### PR TITLE
imapd.c: GETMETADATA shouldn't show DAV mailboxes (unless auth with +DAV)

### PR DESCRIPTION
**Pull request by ksmurchison**

### CODE REVIEW

**Review by rsto — DISMISSED** [review]

**Comment by elliefm** [comment]
This fixes `Caldav.get_legacy_defaultalarm_no_uid` for me:

```
diff --git a/cassandane/Cassandane/Cyrus/Caldav.pm b/cassandane/Cassandane/Cyru>
index 798320ce2..8c96cdd2c 100644
--- a/cassandane/Cassandane/Cyrus/Caldav.pm
+++ b/cassandane/Cassandane/Cyrus/Caldav.pm
@@ -5916,13 +5916,15 @@ EOF
 }
 
 sub test_get_legacy_defaultalarm_no_uid
-    :min_version_3_9 :needs_component_jmap
+    :min_version_3_9 :needs_component_jmap :MagicPlus
 {
     my ($self) = @_;
 
     my $jmap = $self->{jmap};
     my $caldav = $self->{caldav};
-    my $imap = $self->{store}->get_client();
+    my $plusstore = $self->{instance}->get_service('imap'
+        )->create_store(username => 'cassandane+dav');
+    my $imap = $plusstore->get_client();
 
     xlog $self, "Pretend as if JMAP default alarm migration never happened";
     $imap->setmetadata("#calendars.Default",
```

And this fixes `JMAPCalendars.admin_migrate39_defaultalerts`:

```
diff --git a/cassandane/tiny-tests/JMAPCalendars/admin-migrate39-defaultalerts >
index 1240bc12c..10229c6d9 100644
--- a/cassandane/tiny-tests/JMAPCalendars/admin-migrate39-defaultalerts
+++ b/cassandane/tiny-tests/JMAPCalendars/admin-migrate39-defaultalerts
@@ -452,7 +452,9 @@ sub create_legacy_calendar
 {
     my ($self, $name) = @_;
     my $caldav = $self->{caldav};
-    my $imap = $self->{store}->get_client();
+    my $plusstore = $self->{instance}->get_service('imap'
+        )->create_store(username => 'cassandane+dav');
+    my $imap = $plusstore->get_client();
 
     xlog $self, "Create calendar named $name";
     my $calendarId = $caldav->NewCalendar({name => $name});
@@ -469,7 +471,9 @@ sub create_legacy_calendar
 sub set_caldav_datetime_alarms
 {
     my ($self, $calendarId, $valarms) = @_;
-    my $imap = $self->{store}->get_client();
+    my $plusstore = $self->{instance}->get_service('imap'
+        )->create_store(username => 'cassandane+dav');
+    my $imap = $plusstore->get_client();
 
     my $mboxname = '#calendars';
     $mboxname .= ".$calendarId" if $calendarId;
```

**Comment by elliefm** [comment]
@ksmurchison I have a test for this case that I made last week when reproducing the original report.  It fails on master, but passes with your fix.  Do you want me to just push it straight to your branch, or put it up as a separate PR?  

Or you can just import it directly yourself if you want; it's here: https://github.com/cyrusimap/cyrus-imapd/compare/master...elliefm:cyrus-imapd:v39/4732-getmetadata-jmap-folders

**Comment by ksmurchison** [comment]
@elliefm go ahead and push it to my branch if you want

**Comment by elliefm** [comment]
@ksmurchison Done, and I added the +dav patches from my earlier comment too while I was in there.  Hopefully we'll see CI start passing... 🤞

**Comment by ksmurchison** [comment]
👍

**Comment by elliefm** [comment]
@rsto CI is passing now, can you re-review please?  I can't cause I have commits on the branch now 😅

**Review by rsto — APPROVED** [review]

**Pull request merged**
