### PR TITLE
notify/nodifyd.c: update synopsis

### PR DESCRIPTION
**Pull request by dilyanpalauzov**

### CODE REVIEW

**Comment by dilyanpalauzov** [comment]
Can this make progress, please?

**Comment by rsto** [comment]
@dilyanpalauzov I do not understand the suggested change. The updated usage synopsis documents argument options that are not handled by notifyd's getopt argument parsing. Am I missing something here?

**Comment by dilyanpalauzov** [comment]
The parameters are documented at https://www.cyrusimap.org/imap/reference/manpages/systemcommands/notifyd.html . In addition `getopt()` handles the `m:`ethod parameter.

**Comment by rsto** [comment]
Right, my bad. These arguments are processed by `master` before it calls `service_init`. Would you please change `EC_USAGE` to `EX_USAGE` as return status?

**Review by rsto — APPROVED** [review]

**Comment by rsto** [comment]
Thanks, sorry that this got not handled earlier.

**Pull request merged**
