### PR TITLE
imapd.c: remove support for SCAN command

### PR DESCRIPTION
**Pull request by ksmurchison**
Do not merge until we get sufficient feedback from info-cyrus that no clients actually use this.   The latest report from FM-connected clients shows that none of them use SCAN.

### CODE REVIEW

**Review by rsto — APPROVED** [review]

**Review by elliefm — CHANGES_REQUESTED** [review]
This needs a changes file

**Comment by elliefm** [comment]
Does this have #4924 's commits embedded in it too?

**Comment by ksmurchison** [comment]
> This needs a changes file

Done.

**Review by elliefm — APPROVED** [review]
Thanks

**Pull request merged**
