### PR TITLE
jmap_contact_from_vcard: be safe against X-ABLabel with no group

### PR DESCRIPTION
**Pull request by brong**

### CODE REVIEW

**Comment by ksmurchison** [comment]
@brong After looking at this again, I wonder if we should just be ignoring X-ABLabel if it doesn't have a group because it can't be assigned to a property anyways.

**Comment by ksmurchison** [comment]
https://github.com/cyrusimap/cyrus-imapd/pull/3459 has a simpler, alternate fix (no need to track labels unassociated with another property).

Tested here:

**Review by rsto — APPROVED** [review]
Looks good to me

**Comment by ksmurchison** [comment]
Closing due to #3459 being merged

**Pull request closed without merging**
