### PR TITLE
EmailSubmission/set interim identityId fix

### PR DESCRIPTION
**Pull request by ksmurchison**
Temporary hack until we deploy #3728, as discussed with rjbs and alh

### CODE REVIEW

**Review by rsto — APPROVED** [review]
Looks good to me as a temporary fix. I assume we do not merge this on master, but rather just label it include-in-fastmail?

**Comment by brong** [comment]
I have tagged this include-in-fastmail and will get it deployed tomorrow.  Left it too late today!

**Review by brong — APPROVED** [review]
Yeah looks great as an interim workaround.

**Comment by ksmurchison** [comment]
No longer necessary due to https://github.com/cyrusimap/cyrus-imapd/pull/3728

**Pull request closed without merging**
