### PR TITLE
Sieve: update to latest processcalendar spec

### PR DESCRIPTION
**Pull request by ksmurchison**
- will continue to execute processimp bytecode
- upgrades processimip to processcalendar at parse/compile time

This supersedes #4703

### CODE REVIEW

**Review by elliefm — COMMENTED** [review]
Looks good, though a few nits with suggestions, and maybe a bug in sieve_listextensions?

**Review by rsto — COMMENTED** [review]
Generally looks good to me. In addition to what @elliefm found I wonder if this PR also could switch all existing `processimip` tests to use `processcalendar`? A separate test could then assert that the `processimip` capability still is supported.

**Review by elliefm — APPROVED** [review]
Nice

**Review by rsto — APPROVED** [review]
great!

**Pull request merged**
