### PR TITLE
ctl_mboxlist: support uuid mailboxes in ctl_mboxlist -v

### LINKED ISSUE #4187: ctl_mboxlist -v needs to be able to report broken uuid mailboxes
This thing looks at everything in the mailboxes.db and everything on the spool, and reports things that are missing from one or the other.

Ken observes that it doesn't currently seem able to deal with uuid mailboxes.

### PR DESCRIPTION
**Pull request by a-tze**
Fixes #4187

### CODE REVIEW

**Comment by a-tze** [comment]
Sorry for the force-pushs.. but now I'm really finished and it seems to fix #4369 as well.

**Comment by a-tze** [comment]
Probably fixes #1738 as well.

**Review by ksmurchison — APPROVED** [review]
This looks sane to me.
I wonder if we could use a ptrarray or dynarray for found_list rather than have it do its own memory management

**Comment by a-tze** [comment]
Do you mean for the items of found_list or for the strings contained/copied within?

I don't think that the memory management of the found_list is so terrible. The double-capacity realloc logic could use an upper limit so it doesnt blow off the roof in extreme situations, but I think the string copy operations of the things contained in the found_list are more relevant regarding performance and memory footprint.

**Comment by ksmurchison** [comment]
I was talking about found_list. ptrarray was designed for this exact purpose. But I believe the code that you are tweaking predates ptrarray.

**Comment by a-tze** [comment]
Let me have a look into it. If the found_list is not used in the other command implementation of ctl_mboxlist, a refactoring could be a good thing.

**Comment by a-tze** [comment]
Refactoring done. Could someone possibly do this workflow approval thing?

**Comment by a-tze** [comment]
added the Signed-off-by header that the auto-check complained about.

**Comment by a-tze** [comment]
ping :)

**Review by ksmurchison — APPROVED** [review]

**Comment by elliefm** [comment]
When backporting this, it'll also need 3be3f1699

**Comment by a-tze** [comment]
@elliefm Has this been a "note for self" or should I ammend that commit here? :)

**Comment by elliefm** [comment]
That one's for me, sorry for confusion :)

**Pull request merged**
