### PR TITLE
Sieve

### PR DESCRIPTION
**Pull request by jsoref**
This is split from #73

It's quite likely that I broke this while trying to repeat what it was doing. I'm not really in a position to build things. But I'm happy to split pieces out if that's remotely helpful.

### CODE REVIEW

**Comment by elliefm** [comment]
Ken, can you review this please?  You've been in the sieve code recently and might still have it mentally swapped in :)

**Comment by ksmurchison** [comment]
jsoref: please explain the envelope test a bit more.  Are you trying to test against a null reverse-path (e.g. MAIL FROM:<> )?

**Comment by jsoref** [comment]
I can't, this is written by @dilyanpalauzov

**Comment by jsoref** [comment]
@ksmurchison: from reading the comment / code, that does seem to be the spirit.
(I may update this to drop the other commits, but again, I'm not the original author, just trying to help the code move forward.)

**Comment by ksmurchison** [comment]
Fixed in commit
https://github.com/cyrusimap/cyrus-imapd/commit/5a22a67f260988bb07bc5272a1a220022763e15a

**Comment by jsoref** [comment]
@ksmurchison: cool.

If someone would like to go through https://github.com/jsoref/cyrus-imapd/commits/makefile-changes and figure out how to properly achieve the spirit of them (instead of the commits as is),  #73 could finally be closed.
(I could make a PR for it, or recycle this one, but those changes really aren't close to correct, whereas @elliefm had indicated the changes I cherrypicked from #73 were pretty close to correct+welcome.)

**Comment by ksmurchison** [comment]
I'd make a separate pull request for this

**Comment by jsoref** [comment]
done: #1969

**Pull request closed without merging**
