### PR TITLE
squatter: add experimental -M and -D options

### PR DESCRIPTION
**Pull request by rsto**
-M allows to define a seqset of UIDs to consider during indexing. Multiple -M options may be specified. The UID sequence set is evaluated across mailboxes.

-D allows to define an alternative directory to generate the activefile and search indexes in.

Both options are experimental and mainly useful for debugging.

Basic tests are at: https://github.com/cyrusimap/cassandane/tree/squatter_indexmsg

### CODE REVIEW

**Comment by brong** [comment]
Removing this from fastmail builds due to conflict with #3266

**Comment by rsto** [comment]
Let's rebase and merge that into master, right?

**Comment by brong** [comment]
@rsto - do we still want to go ahead with this?

**Comment by rsto** [comment]
I'd say yes, but only as an undocumented feature. I just let it linger until the patch for long argument options landed.

**Comment by elliefm** [comment]
> Both options are experimental and mainly useful for debugging.

> I'd say yes, but only as an undocumented feature.

I'd say document them anyway, and be explicit that they're experimental and mainly useful for debugging.  It'll save us questions about "what are these undocumented things for" later, and might even net us useful feedback from others experimenting with them.

**Pull request closed without merging**
