### PR TITLE
imap/xapian_wrap.cpp: further C++ tweaks

### PR DESCRIPTION
**Pull request by dilyanpalauzov**

### CODE REVIEW

**Comment by rsto** [comment]
I get lots of failure in the Cassandane.SearchFuzzy test suite when running this branch forked from master. Could you please validate this PR with Cassandane and the latest cyruslibs build?

**Comment by dilyanpalauzov** [comment]
I assmed, that after
```C++
Xapian::Query q1, q2 {OP_OR, "a", "b"};
q1 |= q2;
```
q1.get_type() will be OP_OR, but it is LEAF_MATCH_NOTHING.

**Comment by rsto** [comment]
Thanks! Confirmed passing all Cassandane SearchFuzzy tests and the JMAP test suites.

**Comment by dilyanpalauzov** [comment]
On line 919: ` *q = db->parser->parse_query(lmatch, flags, prefix);` I have forgotten | before =.

**Pull request merged**
