### PR TITLE
2.5 sphinx compatibility fixes

### PR DESCRIPTION
**Pull request by elliefm**
Currently, documentation generation on the cyrus-imapd-2.5 branch requires Sphinx 1.x.  We need to generate these docs for the website, which means we keep needing to pin the website builder on Sphinx 1.x.  That gets harder and harder as the years pass...

We already support Sphinx 3+ for cyrus-imapd-3.0 and later.  This PR minimally backports a small handful of fixes to 2.5, so that we can theoretically upgrade the website builder to at least Sphinx 3.

It works for me, with:

```
$sphinx-build --version
sphinx-build 3.4.3
```

I would usually just land this directly on the 2.5 branch without a PR, since these are all just backports of existing commits.  But I want to know whether it works for whatever Sphinx versions you have.

**Reviewers:** please advise your sphinx-build version, and test as follows, starting with a clean repository.  You do not need to run configure (and it probably wouldn't work anyway)
1. `make -C docsrc html` => expect a boatload of warnings, but it should succeed.  It will generate the 2.5 version of the website at `docsrc/build/html/index.html`.  Open this in a browser and click around a little, it should be similar to http://www.cyrusimap.org/2.5/
2. `make -C docsrc man` => also lots of warnings, but should succeed.  Man pages will be generated in `docsrc/build/man`.  Check those files aren't empty, and check a few to see if the formatting looks okay with e.g. `man docsrc/build/man/imapd.conf.5` etc.

### CODE REVIEW

**Review by rsto — APPROVED** [review]
Works for me running Sphinx v3.4.3

**Comment by rsto** [comment]
this fails for me with

    $ make -C docsrc html
    make: Entering directory '/home/rsto/cyrus/cyrus-imapd/docsrc'
    creating imap/admin/systemcommands/cyradm.rst
    ../tools/perl2rst cyradm < ../perl/imap/IMAP/Shell.pm > ./imap/admin/systemcommands/cyradm.rst
    creating imap/admin/configs/imapd.conf.rst
    ../tools/config2rst ../lib/imapoptions > ./imap/admin/configs/imapd.conf.rst
    sphinx-build -b html -d build/doctrees  -n . build/html
    Running Sphinx v3.4.3

    Extension error:
    Could not import extension sphinxlocal.builders.manpage (exception: cannot import name 'NoUri' from 'sphinx.environment' (/usr/lib/python3/dist-packages/sphinx/environment/__init__.py))
    make: *** [Makefile:66: html] Error 2
    make: Leaving directory '/home/rsto/cyrus/cyrus-imapd/docsrc'

same for the man pages

**Comment by elliefm** [comment]
> this fails for me with
> Could not import extension sphinxlocal.builders.manpage (exception: cannot import name 'NoUri' from 'sphinx.environment' (/usr/lib/python3/dist-packages/sphinx/environment/__init__.py))

You should not be seeing an error like this, because sphinxlocal.builders.manpage _has been removed_ (and therefore cannot possibly be trying to import other things).  This was one of the errors this PR fixes.  Are you sure you're running the steps on the correct branch?

I'm expecting you to pull the branch from this PR, and run the test steps on that.  The "view command line instructions" link in the "Review requested" box will show the git commands to copy and paste.

If you run the test steps directly on the `cyrus-imapd-2.5` branch, they'll fail, just like this, because the fixes haven't landed there yet...

**Comment by rsto** [comment]
@elliefm works for me now with `sphinx-build 3.4.3`. I previously ran this on a messed up branch.

**Review by rsto — APPROVED** [review]

**Pull request merged**
