### PR TITLE
Preserve the original partition of a (sub-)mailbox when using XFER

### PR DESCRIPTION
**Pull request by kanarip**
Preserve the partition of a (sub-)mailbox when using XFER, rather than use the highest-level mailbox of the hierarchy transferred as the target partition for all mailboxes in the hierarchy.

The use-case is mailbox hierarchies split over multiple partitions.

Example scenario;

  * `user.john` resides on the default partition, and `user.john.Archive` resides on a partition archive.

  * While 'default' is fast, expensive storage, we have only 1GB of it.

  * While 'archive' is slow, cheap storage, we have a few TBs of it.

  * The size of `user.john.Archive` is > 1 GB.

With this patch, unless a partition is explicitly specified to the issuing of the XFER command, any mailbox residing on;

  * the local default partition will be replicated to the target default partition,

  * a local non-default partition will be replicated to the target partition of the same name.

I do not believe this patch makes any sense for master, as I understand XFER has transitioned to the sync protocol, but please do correct me if a similar scenario may exist there, that deserves attention.

### CODE REVIEW

**Comment by kanarip** [comment]
Please note that the change to RFC 4466 style inclusion of the target partition in the changed LOCALCREATE command issuance has to do with a later change I'm yet to create a pull request for.

**Comment by elliefm** [comment]
What happens if the remote server has the higher level partition, but not the submailbox partition(s)?

Will it:

a) fall back to the original behaviour of just putting the whole hierarchy on the one partition?
b) fail to copy the submailboxes, causing the whole XFER to fail?
c) fail to copy the submailboxes, but the XFER still reports "success"?

I don't really care much one way or other between a or b; but c would be unacceptable

**Comment by kanarip** [comment]
The target backend for the transfer should respond as if an invalid partition was specified, meaning that it should bail out on the XFER -- so option b).

**Comment by rsto** [comment]
The XFER command is deprecated.

**Pull request closed without merging**
