### PR TITLE
http_ws: really do telemetry log each request separately!

### PR DESCRIPTION
**Pull request by brong**

### CODE REVIEW

**Comment by ksmurchison** [comment]
Why does each JMAP request have to be logged separately?  Why can't this be treated like an IMAP connection with multiple commands?

**Comment by brong** [comment]
@ksmurchison we log them all separately so we can easily replay a single one using the replayjmap tool.

**Comment by rjbs** [comment]
@brong Are you looking to get this merged to master, or to keep it as a downstream customization?

**Comment by brong** [comment]
Yes, merge to master.  IMAP is stateful, so you need to keep the connection together.  For websockets you don't, and each request is independent.

**Pull request merged**
