### PR TITLE
ci: Travis to use cyrus-buster instead of cyrus-jessie

### PR DESCRIPTION
**Pull request by ajaysusarla**
While the tag was `cyrus-jessie`, we were building `buster`, so named
the tag appropriatedly.

### CODE REVIEW

**Comment by ajaysusarla** [comment]
The newly tagged docker images are available here:https://hub.docker.com/repository/docker/cyrusimapdocker/cyrus-buster

**Review by elliefm — APPROVED** [review]

**Comment by elliefm** [comment]
Do you happen to know if Travis always uses the ".travis.yml" from the master branch, or does it use the ".travis.yml" from the branch it's building?

In the latter case I guess I'll need to cherry-pick this back to the stable branches too

**Comment by elliefm** [comment]
No worries, I'll get it picked back shortly then

**Comment by ajaysusarla** [comment]
> No worries, I'll get it picked back shortly then

@elliefm do we want that though? The old tag will continue to exist. The reason I think we should not do it is because, the cyrus-libs that are built into the images will always be the latest. So we might have a state where the branches rely on some versions of cyrus-libs, which don't exist anymore.
Although, we have that problem even now.

**Comment by elliefm** [comment]
For me it's mostly about not wanting the additional load of keeping track of which branches use which docker image.

If we wind up with breaking changes due to cyruslibs moving forward, IMO we can just deal with that when it happens... perhaps by saying "this release is so old that we're no longer going to bother running CI for it".

We already have problems like this for 3.0 (which uses libical features that are now deprecated), and we get around that by building 3.0 with -Wno-error so the deprecated functions are just warnings instead of errors.

**Comment by ajaysusarla** [comment]
ack! that sounds reasonable!

**Comment by elliefm** [comment]
This is now on the 3.6, 3.4, and 3.2 branches

For 3.0, looks like we don't use docker at all (the .travis.yml is very different and the cherry-pick fails with loads of conflicts), so it can just stay how it is.

**Pull request merged**
