### PR TITLE
[imap] Use an enum in jmapmsg_from_body().

### PR DESCRIPTION
**Pull request by ajaysusarla**
`jmapmsg_from_body()` uses an integer for `is_embeded` variable, changing that
to an enum for clarity.

### CODE REVIEW

**Comment by ajaysusarla** [comment]
@rsto I might not have named the `enum` appropriately. Please do suggest a different name if you think it isn't appropriate.

**Comment by rsto** [comment]
@ajaysusarla I think the enums are a good idea, but the naming is currently not correct. I don't expect there to be ever more than two possible values: either the message is the top message, or it's an attached message (a mail body of type  `message/rfc822`).

I suggest `MSG_IS_TOP=0` and `MSG_IS_ATTACHED=1`?

There's a bunch of alternatives: a "top" message could also be named the "root" message, whereas an "attached" message is also referred to as "embedded" or "encapsulated" (the latter term is used in the [definition](https://www.w3.org/Protocols/rfc1341/rfc1341.html) of the `message/rfc822` subtype). Do you have a preference?

**Comment by ajaysusarla** [comment]
@rsto Thanks for your feedback. I think `MSG_IS_ROOT = 0` and `MSG_IS_ATTACHED = 1` make sense according to what you say.  Accordingly, our `enum` will be:
```
typedef enum MsgBodyType {
        MSG_IS_ROOT = 0,
        MSG_IS_ATTACHED = 1,
} MsgBodyType;
```
Do you think the `enum` itself should be named as `MsgType` instead of `MsgBodyType`? According to the definition you linked to, it seems it should be `MsgContentType`.

**Comment by rsto** [comment]
I'd prefer `MsgType`, content type could be a lot of things.

**Comment by ajaysusarla** [comment]
@rsto Done! I've updated the patch, please review when possible. Thanks again!

**Comment by rsto** [comment]
thanks! lgtm

**Pull request merged**
