### PR TITLE
Doc restructure: a simpler hierarchy

### PR DESCRIPTION
**Pull request by nicolan**
Making the initial left hand navigation simpler, easier to follow and faster to locate information as it's less cluttered.

Splitting up the old concepts guide into Concepts and Admin, and removing leftover html cruft that was from a time long ago.

Restructuring some of the content to get the hierarchy easier to read and navigate.

### CODE REVIEW

**Comment by elliefm** [comment]
Looks good at a quick look through now, I'll pull it down and try it out properly tomorrow

**Comment by nicolan** [comment]
The file structure on disk does not match the new hierarchy visually. And I think it should correlate for ease of management, but I'm holding off until I've finished further restructure and subdivision so the physical shuffle can be done in one lot.

**Comment by elliefm** [comment]
Just pulled it onto my local repository, built docs, and it's looking good, no warnings or errors or anything.

Do you want this merged as is (and then presumably the rest of the restructure becomes a separate pull request, later), or do you want to leave it hanging for a bit and keep working further into it?

**Comment by nicolan** [comment]
Merge as-is, I reckon. It looks shiny enough that it's worth pushing live. If I wait until it's "all done", this won't get merged until 2018.,

**Comment by elliefm** [comment]
Done :)

**Pull request merged**
