### PR TITLE
Remove SSE4.2 dependency checks and related code

### LINKED ISSUE #3102: Remove cld2 and SSE4.2 from configure.ac
@elliefm,

I see that the cld2 detection code is still in configure.ac. Shouldn't it be removed based on what we've discussed recently on cyrus-devel@ (i.e. cld2 is not used anywhere and was included by mistake)?

And related, recently there was a thread ("cyrus-imap buildin: sse extention") in info-cyrus@ about SSE4.2 compilation for CRC32c algo. I've commented that maybe the detection and informational code should also be removed from configure.ac as it is not used in any way at this moment and there are no plans to make it work, so to remove the confusion and simplify the code.

I can submit a PR if you prefer (without the merge mess this time : ).

### PR DESCRIPTION
**Pull request by anatoli26**
SSE4.2 was checked to use a hardware native x86 processors instruction
for CRC32c calculation. Nevertheless, its result was not compatible with
the existing CRC32 algorithm, so it was never actually used anywhere in
the project, but the code was still getting compiled introducing
distribution issues for those processors that had no such instruction.

Actually, there probably was no such issue in practice as there was a
check at runtime in crc32c_init() for availability of the instruction,
though it might have had some issues in some corner cases on some
platforms and it was confusing for the maintainers.

In the future if a need arises to revive this functionality, just undo
this commit.

Closes #3102 (2/2)

### CODE REVIEW

**Comment by elliefm** [comment]
Thanks, this looks pretty tidy!

I've added it to the agenda for the cyrus-devel meeting next week, to figure out whether we'll remove it, ignore it, make it configurable, or something else

**Comment by anatoli26** [comment]
@elliefm, could you please cherry-pick this commit (+ the one from Ken) to the 3.2 branch?

**Comment by elliefm** [comment]
Oh whoops, thanks for the reminder.  I think I meant to do this, but since Bron did the merge rather than me, the next step slipped my mind.  Doh!

I've just cherry-picked both commits locally, and will push them upstream once the tests finish.

**Comment by elliefm** [comment]
Done :)

**Pull request merged**
