### PR TITLE
Update JMAP contacts support to IETF standards

### PR DESCRIPTION
**Pull request by ksmurchison**
[https://datatracker.ietf.org/doc/draft-ietf-jmap-contacts/](url)
[https://datatracker.ietf.org/doc/draft-ietf-calext-jscontact/](url)
[https://datatracker.ietf.org/doc/draft-ietf-calext-jscontact-vcard/](url)
[https://datatracker.ietf.org/doc/draft-ietf-calext-vcard-jscontact-extensions/](url)

### CODE REVIEW

**Comment by elliefm** [comment]
This was merged with failing CI checks 👎

**Comment by ksmurchison** [comment]
What's failing?

**Comment by elliefm** [comment]
Should be fixed by #4684 -- will find out when its checks finish...

**Comment by elliefm** [comment]
It introduced a dependency on XML::Simple, which neither the docker image nor the workflow script was installing

**Pull request merged**
