### PR TITLE
http_caldav.c: do not require tzdist module for calendar-timezone-id

### PR DESCRIPTION
**Pull request by rsto**

### CODE REVIEW

**Review by ksmurchison — COMMENTED** [review]
This works, but couldn't we just always set ALLOW_CAL_NOTZ?

**Comment by rsto** [comment]
I thought that, too. We could but it would enable a couple of other features, too.

**Review by ksmurchison — COMMENTED** [review]
Yeah, you're right.  This is probably safer for now.  However, I also think we want this change in propfind_timezone() as well.

**Comment by rsto** [comment]
Agreed. Applied change and restarted CI.

**Review by ksmurchison — APPROVED** [review]

**Comment by rsto** [comment]
Could not reproduce CI failures on local build. Most likely a VM glitch. Rerunning CI.

**Comment by dilyanpalauzov** [comment]
proppatch_tzid() could reject acting on Scheduling Outbox and Attachments.

caldav_get_calendar_tz() looks for the timezone in the collection and in the calendar-homeset.  It is reasonable to allow proppatch_tzid() and proppatch_timezone() when req_tgt.userid is set, fctx->req_tgt->resource is not set, and irrespective of whether fctx->req_tgt->collection is NULL.

**Pull request merged**
