### PR TITLE
Convert and move doc/internal

### PR DESCRIPTION
**Pull request by postilion**
This commit involves converting all of the documentation in the old
/doc/internal location into RestructuredText, and puts it in various
branches of /docsrc/imap/developer:

	guidance - Documents which explain how or why things are done
	thoughts - Random notes and ideas
	API - Application Programming Interfaces

Many of the source documentation is very old, and no real effort
has been made to ensure that it is up to date or accurate.

Also, conf.py was updated to bring the copyright up to 2018.

Addresses #2276  &  #2279

### CODE REVIEW

**Comment by postilion** [comment]
@nicolan @brong @elliefm Please review for completeness and let me know if you approve of the  general idea of the new layout in the /docsrc/imap/developer branch(es).

Thanks in advance!
-nic

**Comment by elliefm** [comment]
I like the layout. :)

I needed the following patch to shut up some warnings from sphinx, do you mind adding it to your branch?

```
diff --git a/docsrc/imap/developer/guidance/hacking.rst b/docsrc/imap/developer/guidance/hacking.rst
index 769088933..2ae21fef0 100644
--- a/docsrc/imap/developer/guidance/hacking.rst
+++ b/docsrc/imap/developer/guidance/hacking.rst
@@ -79,7 +79,7 @@ map_refresh and map_free
     to open the file descriptors O_RDWR, especially if the file
     descriptors could possibly be used for writing elsewhere in the
     code. Some operating systems REQUIRE file descriptors that are
-    ``mmap()``ed to be opened O_RDWR, so just do it.
+    ``mmap()``-ed to be opened O_RDWR, so just do it.
 
 Network Functions
 -----------------
diff --git a/docsrc/imap/developer/guidance/mailbox-format.rst b/docsrc/imap/developer/guidance/mailbox-format.rst
index a8e720db4..a9df8aa21 100644
--- a/docsrc/imap/developer/guidance/mailbox-format.rst
+++ b/docsrc/imap/developer/guidance/mailbox-format.rst
@@ -295,36 +295,36 @@ The index header contains the following information, in order:
     happens (so that only one is synced), we do not provide bad data to
     the user. This is also backed by having individual cache checksums
     on each record.
-Format (4 bytes)
+ Format (4 bytes)
     Basically obsolete (indicates netnews or regular).
-Minor Version (4 bytes)
+ Minor Version (4 bytes)
     Indicates the version number of the index file. This can be used for
     on-the-fly upgrades of the index and cache files.
-Start Offset (4 bytes)
+ Start Offset (4 bytes)
     Size of index header.
-Record Size (4 bytes)
+ Record Size (4 bytes)
     Size of an index record.
-Num Records (4 bytes)
+ Num Records (4 bytes)
     How many records are in this index (including records for expunged
     records. See below for "Exists" which has moved from pre-version 12
     files.
-Last Appenddate (4 bytes)
+ Last Appenddate (4 bytes)
     (time\_t) of the last time a message was appended
-Last UID (4 bytes)
+ Last UID (4 bytes)
     Highest UID of all messages in the mailbox (UIDNEXT - 1).
-Quota Mailbox Used (8 bytes)
+ Quota Mailbox Used (8 bytes)
     Total amount of storage used by all of the messages in the mailbox.
     Platforms that don't support 64-bit integers only use the last 4
     bytes.
-POP3 Last Login (4 bytes)
+ POP3 Last Login (4 bytes)
     (time\_t) of the last pop3 login to this INBOX, used to enforce the
     "poptimeout" ``imapd.conf`` option.
-UIDvalidity (4 bytes)
+ UIDvalidity (4 bytes)
     The UID validitiy of this mailbox. Cyrus currently uses the
     ``time()`` when this mailbox was created.
-Deleted, Answered, and Flagged (4 bytes each)
+ Deleted, Answered, and Flagged (4 bytes each)
     Counts of how many messages have each flag.
-Mailbox Options (4 bytes)
+ Mailbox Options (4 bytes)
     Bitmask of mailbox options, consisting of any combination of the
     following:
 
@@ -351,44 +351,44 @@ Mailbox Options (4 bytes)
         to finish their current operation first without files
         disappearing from under them!
 
-Leaked Cache (4 bytes)
+ Leaked Cache (4 bytes)
     Number of leaked records in the cache file.
-Highest ModSeq (8 bytes)
+ Highest ModSeq (8 bytes)
     Highest Modification Sequence of all the messages in the mailbox
     (CONDSTORE).
-Deleted ModSeq (8 bytes)
+ Deleted ModSeq (8 bytes)
     Lowest Modification Sequence before which expunged message data may
     have been purged from the mailbox and forgotten (CONDSTORE/QRESYNC
     support).
-Exists (4 bytes)
+ Exists (4 bytes)
     See NumRecords above. This is the count of non-expunged records in
     the mailbox and corresponds to the IMAP status item "EXISTS".
-First Expunged (4 bytes)
+ First Expunged (4 bytes)
     lowest modified time of an expunged message in this mailbox (or zero
     if there are no expunged messages) - used to determine if the
     mailbox needs repacking.
-Last Repack Time (4 bytes)
+ Last Repack Time (4 bytes)
     a timestamp for the last repack, to ensure repacks aren't done too
     close together if expunges were closely spaced
-Header File CRC (4 bytes)
+ Header File CRC (4 bytes)
     CRC32 value of the bytes in the ``cyrus.header`` file for this
     mailbox. Must be rewritten whenever the cyrus.header file is changed
     (see locking considerations above - this is why the cyrus.index must
     be exclusively locked!)
-Sync CRC (4 bytes)
+ Sync CRC (4 bytes)
     An XOR of the CRC32 of a specially generated value for each of the
     non-expunged records in this mailbox. This is a cached value which
     allows the replication subsystem to quickly determine that all
     non-expunged records in a mailbox are in sync and detect possible
     "split brain" scenarios with low bandwidth use.
-Recent UID (4 bytes)
+ Recent UID (4 bytes)
     The highest UID last time an IMAP client logged in as the mailbox
     owner (or anybody if SHAREDSEEN is enabled) selected this mailbox.
     Used to generate the \\Recent flags in IMAP
-Recent Time (4 bytes)
+ Recent Time (4 bytes)
     Used for consistency with the seen\_db code, but probably not
     actually necessary. Oh well
-Header CRC (4 bytes)
+ Header CRC (4 bytes)
     Must always be the LAST record of the header. This is the CRC32 of
     the actual bytes on disk (network order format) for the rest of the
     cyrus.index. By keeping it last, it can be easily calculated with
diff --git a/docsrc/imap/developer/guidance/replication_protocol.rst b/docsrc/imap/developer/guidance/replication_protocol.rst
index 0ea394629..c13cc7381 100644
--- a/docsrc/imap/developer/guidance/replication_protocol.rst
+++ b/docsrc/imap/developer/guidance/replication_protocol.rst
@@ -1,4 +1,4 @@
-.. _imap-developer-guidance-replication-protocol
+.. _imap-developer-guidance-replication-protocol:
 
 ..  Note: This document was converted from the original by Nic Bernstein
     (Onlight).  Any formatting mistakes are my fault and not the
```

**Comment by elliefm** [comment]
You missed this little one hiding at the end! :(

```
diff --git a/docsrc/imap/developer/guidance/replication_protocol.rst b/docsrc/imap/developer/guidance/replication_protocol.rst
index 0ea394629..c13cc7381 100644
--- a/docsrc/imap/developer/guidance/replication_protocol.rst
+++ b/docsrc/imap/developer/guidance/replication_protocol.rst
@@ -1,4 +1,4 @@
-.. _imap-developer-guidance-replication-protocol
+.. _imap-developer-guidance-replication-protocol:
 
 ..  Note: This document was converted from the original by Nic Bernstein
     (Onlight).  Any formatting mistakes are my fault and not the
```

**Comment by postilion** [comment]
@elliefm Fixed!

**Comment by elliefm** [comment]
Thanks! :)

**Pull request merged**
