### PR TITLE
Not all systems have memrchr()

### PR DESCRIPTION
**Pull request by citrus-it**
I've just finished packaging Cyrus imapd for OmniOS which is an illumos (née OpenSolaris) distribution.

There were a few small compatibility changes needed, this is the first.

### CODE REVIEW

**Comment by citrus-it** [comment]
Alternatively, the one place that uses `memrchr()` could be changed to not use it - let me know your preference.

**Comment by elliefm** [comment]
Thanks.  I had a quick look to check the complexity of just not using `memrchr()`, and the one place it's "actually used" is here:

https://github.com/cyrusimap/cyrus-imapd/blob/4376a87773f709516105b84e3cf12b7d55775a55/imap/conversations.c#L528-L533

Which you can see has already been disabled by bd2a3787f9 on the master branch.  But I guess you're packaging 3.2, which doesn't have this commit, and therefore still needs `memrchr()`.

Rather than adding a memrchr implementation, maybe we just need to apply the same change to 3.2 as was done on master.  @brong @ksmurchison what's the production ramification of suddenly allowing multiple '@'s in msgids here?  Will admins need to rebuild their conversationsdb's?  Is it pretty seamless?

**Comment by ksmurchison** [comment]
I'll defer the conv.db question to @brong, but if we keep this check I don't see why we couldn't use strchr() and strrchr() instead.

**Comment by brong** [comment]
strrchr would be fine for this case.  There are some places where memchr is needed because the buffer could contain NULLs, but not here.

**Comment by brong** [comment]
(also I don't really care that much about this test - we could drop it)

**Comment by ksmurchison** [comment]
I don't see any harm in adding a replacement for memrchr() regardless of whether we keep the check in conversations.c.  The source won't be compiled if we don't need it.

**Comment by citrus-it** [comment]
Let's go for this then and avoid the non-standard memrchr() entirely. I know it's disabled code in master - can this patch be back-ported to 3.2.<next>?

**Comment by elliefm** [comment]
I applied the merge locally and then cherry-picked the commit to 3.2 to see what would happen.  Builds fine, but one of the conversations unit tests fails in three places:

```
Suite: conversations
  Test: open ...passed
  Test: getset ...passed
  Test: abort ...passed
  Test: prune ...FAILED
    1. ./cunit/conversations.testc:203  - nseen >= 3
    2. ./cunit/conversations.testc:204  - ndeleted >= 2
    3. ./cunit/conversations.testc:221  - CU_ASSERT_EQUAL(arrayu64_size(&cids)=1,0=0)
  Test: two ...passed
  Test: cid_encode ...passed
  Test: cid_decode ...passed
  Test: folder_rename ...passed
  Test: folders ...passed
  Test: folder_ordering ...passed
  Test: dump ...passed
  Test: subject_normalise ...passed
```

Guessing at the cause, the `msgid` buffer is probably not 0-terminated (which is unsurprising, since we're passing around an explicit length with it), so it's not safe to use the `str...` functions on it.  Which might be the real reason why we used `memchr` and `memrchr` to begin with.

The internet suggests `strnchr` and `strnrchr` (which each take a length parameter) might exist, except they also don't seem to consistently exist, so that's hardly a solution to "memrchr might not exist"...

At this point I wonder if maybe you should just patch this within your package -- either by grabbing bd2a3787f9 from the master branch (to disable this check altogether), or by including a memrchr replacement.  I'm not sure there's an option here that's sensible to include upstream.

**Comment by citrus-it** [comment]
Thanks for checking - I'm surprised that msgids can contain embedded NULs, but fair enough.

Back to this then, including a memrchr() replacement, which is the local patch I'm already carrying.
I could rewrite the existing check to just use memchr() too but I don't think there is any harm in including the replacement when using non-standard functions. As @ksmurchison said, if it is not needed then it won't be compiled.

**Comment by elliefm** [comment]
> I'm surprised that msgids can contain embedded NULs

They can't; but they can be stored in unterminated buffers (e.g. fixed-width field in an mmap'd file...), in which case the `str...` functions overrun the end.

> Back to this then,

Yeah, that looks alright to me.  I can't easily test the replacement function, but I suppose it won't break for anyone who it wasn't already broken for anyway...

**Comment by elliefm** [comment]
This is on the 3.2 branch as 94d0c02555 and will be in the next release.  Thanks :)

**Pull request merged**
