### PR TITLE
runtime toggleable debug logging

### PR DESCRIPTION
**Pull request by elliefm**
This adds an API such that `config_debug` (aka "debug:" in imapd.conf) can be toggled on and off at runtime, and hooks up a signal handler such that SIGUSR1 will toggle it.  The test case tests this with `imapd`, but it should work the same for any Cyrus process (specifically, any process that calls both `cyrus_init()` and `signals_add_handlers()`).

You can already crudely toggle debug logging by changing debug: in imapd.conf and sending master a SIGHUP, but that a) affects all Cyrus process, b) only after they restart and reread the config, and c) also picks up other unrelated config changes.  This PR allows toggling debug logging on or off for a specific process, while that process is already running, and without reloading the config generally.

SIGUSR1 is already used by cunit (for test timeout handling) and Cassandane (as part of hooking a debugger to a running test process), but isn't used by Cyrus itself.  This usage shouldn't clash with the test systems' usages.

### CODE REVIEW

**Comment by elliefm** [comment]
Pre-emptive "do not merge" cause by the time this is reviewed and I see it again we'll be in feature freeze.  Will tag it for FM once approved.

**Review by ksmurchison — APPROVED** [review]
LGTM.

If you don't want to have a special XNOOP command for testing, SELECT/EXAMINE already has a simple DEBUG log line when it completes

**Comment by elliefm** [comment]
I've discarded the xnoop implementation, rewritten the test to use select instead, and added a comment to imapd.c explaining that cmd_select's debug log line is now load bearing, so that anyone trying to change it in the future doesn't get a surprise

**Comment by wolfsage** [comment]
This is amazing, thanks! I haven't played with it yet but would love to see it in action

**Review by ksmurchison — APPROVED** [review]

**Comment by elliefm** [comment]
Won't merge this till after the feature freeze, but I've tagged it include-in-fastmail for now so we can get it into our builds for @wolfsage to play with.  Any issues, let me know, or just untag it.

**Pull request merged**
