### PR TITLE
Avoid returning -1 as 255

### LINKED ISSUE #2122: [2.5/ppc64le]: cunit/parse.testc failures
wrap_getint32() and wrap_getsint32() fail, as they appear to return 255 rather than -1.

### PR DESCRIPTION
**Pull request by kanarip**
Resolves #2122

### CODE REVIEW

**Comment by elliefm** [comment]
This doesn't seem right, these are `int`s all the way down, so no part of them should be converting -1 to 255 unless the platform is only 8bit (which, I'm guessing "ppc64le" is 64-bit).  Converting down to int8_t seems like it might _cause_ `-1==255`, not avoid it??

These functions are explicitly dealing in 32 bit integers so if anything, the correct explicit type should be int32_t?  And if there's an endianness issue that causes some weird `-1=255` conversion then this converting down to an 8bit type won't it, just maybe hide it...

**Comment by kanarip** [comment]
I believe it is an issue related to older versions of the compiler as well, if that helps. GCC 4.7.3 (iirc) on ppc64le does show this weird behaviour, but more up-to-date 6+ and 7+ series (iirc) do not.

**Comment by elliefm** [comment]
Do you still have need to support the older compilers, or can we just close this off?

**Comment by kanarip** [comment]
I can conditionally patch it in my packaging, if it makes no sense to include upstream...

FWIW, this would be RHEL 7 on PPC and ARM -- old, but not too old ;-)

**Pull request closed without merging**
