### PR TITLE
JMAP push

### PR DESCRIPTION
**Pull request by ksmurchison**
Implements JMAP EventSource.

Built on top of https://github.com/cyrusimap/cyrus-imapd/pull/3473

This PR includes all of my previous work on these branches.

### CODE REVIEW

**Review by rsto — COMMENTED** [review]
The txn refactor looks good to me and the JMAP Push implementation, too. Is there any meaningful way to test this, either in Cassandane or unit tests?

**Comment by ksmurchison** [comment]
I can probably make a Cass test for this.

**Comment by ksmurchison** [comment]
Simple Cass test is here: https://github.com/cyrusimap/cassandane/pull/122

To do anything more substantial, we will need an async HTTP client

**Review by rsto — APPROVED** [review]
Looks good to me.

**Pull request merged**
