### PR TITLE
iMIP: Add support for METHOD:PUBLISH (with empty ORGANIZER)

### PR DESCRIPTION
**Pull request by ksmurchison**

### CODE REVIEW

**Review by rsto — COMMENTED** [review]
When I delete the (empty) ORGANIZER property from the iTIP, it gets rejected. Is that on purpose? I wonder what's the practical difference between no ORGANIZER, or an empty-valued one.
I assume that's because of the iTIP standard, but might it make sense to be more lenient here?

**Comment by ksmurchison** [comment]
@rsto libical's restriction checks will cause PUBLISH without ORGANIZER to fail on parsing, unless we override it.

**Comment by rsto** [comment]
OK, not worth the effort then. Thanks.

**Review by rsto — APPROVED** [review]
LGTM

**Pull request merged**
