### PR TITLE
OpenBSD: upstreaming patches

### PR DESCRIPTION
**Pull request by anatoli26**

### CODE REVIEW

**Comment by elliefm** [comment]
Thanks, most of these look straightforward.  But can you please rewrite the commit messages to briefly describe what the commits actually do?  This makes future maintenance a lot easier.  You can look at existing commits (with `git log --format=fuller`) to get an idea of the style we usually use, but it's basically: the file/module/concept being changed, a brief one-line description of the change, and then (optionally, and only if necessary) a longer, more detailed description, or references to relevant github issues/etc.

Since this is a PR, the eventual merge will reference the PR automatically, so in this case you don't need to say "Part of #3129" or whatever, but for example if this were to fix an issue, you would want to reference the issue.  Though, if the whole PR was for a particular single issue, you would probably reference the issue number in the PR description, rather than the individual commits...

Anyway!  For these commits, in order, I would suggest the commit messages should be something like:

* configure.ac: OpenBSD cccdlflags are the same as other BSD's
* [ please drop the LIBRESSL_VERSION_NUMBER commit for now, until we can figure out what it does ]
* byteorder: OpenBSD uses the same endian header as Linux
* fud: don't redefine MAXDOMNAME if already defined

I would also, in each of these commit messages, add something like "This patch was previously contributed to the OpenBSD port", and maybe include the original author, if known/not yourself?  If there are commit messages associated with these patches in the OpenBSD repo, then it would be good to include any extra information from those, too.

I'm not sure if you know how to rewrite commit messages/history, so I'll try to explain:

1) Look at the git log for your openbsd branch (`git log`).  You should see your four commits at the top, followed by the rest of the history.  Copy the sha1 id of the first commit that is _not_ part of the pull request (i.e., the parent commit that your PR follows on from).
2) `git rebase -i <that sha1>`.  This will open an interactive rebase in your text editor, allowing you to rebase the commits since the sha1 you pasted.  You should see four lines starting with "pick", i.e. one for each of your commits, and then a block of comments with instructions.
3) For the "OpenBSD: upstreaming patches, p2" commit (i.e. the LIBRESSL_VERSION_NUMBER one), delete the whole line
4) For the other three lines, replace the word "pick" at the start of the line with "reword"
5) Save the file and exit
6) It will now, one commit at a time, open an editor for you to change the commit message, for each one you said to "reword".   It will contain the original commit message, plus a comment block with instructions.  Edit the commit message appropriately, then save and quit.  Rinse and repeat until you have edited all of them and the rebase is finished.
7) If anything goes wrong at any point, you can just `git rebase --abort` to get back to the original state, and then try again.
8) Your local branch history will now differ from your github branch history, so you will need to use the `-f|--force` when you push it.  Github will update the PR automatically once you push it.

If you get really stuck, let me know, and I'll just do the edits myself here and merge manually instead. :)

**Comment by elliefm** [comment]
[I plan to build and test this locally before I merge it, but I haven't done so yet.  If anyone else looks at this in the meantime, please don't assume that I have done so already!]

So, I'm not sure about this commit: https://github.com/cyrusimap/cyrus-imapd/pull/3129/commits/c965b0006ee6af02e82f4c88d4ab46dd2553cfd0

Here's what it does:

```
     if (strstr(tls_versions, "tls1_3") == NULL) {
-#if (OPENSSL_VERSION_NUMBER >= 0x1010100fL)
+#if (OPENSSL_VERSION_NUMBER >= 0x1010100fL) && !defined(LIBRESSL_VERSION_NUMBER)
         //syslog(LOG_DEBUG, "TLS server engine: Disabled TLSv1.3");
         off |= SSL_OP_NO_TLSv1_3;
 #else
         syslog(LOG_ERR, "ERROR: TLSv1.3 configured, OpenSSL < 1.1.1 insufficient");
 #endif // (OPENSSL_VERSION_NUMBER >= 0x1010100fL)
     }
```

What it looks like to me:

1) tls_versions does not contain "tls1_3", so we want to disable it
2) if our OpenSSL version is new enough to be able to disable it, we add the flag that disables it
3) but if our OpenSSL is not new enough to be able to disable it, we instead log an error message that TLSv1.3 is still enabled, even though the config said to disable it

The patch seems to treating LIBRESSL_VERSION_NUMBER as indicative that TLSv1.3 cannot be disabled, and therefore if LIBRESSL_VERSION_NUMBER is defined, TLSv1.3 will not be disabled, even though the admin wanted to disable it.

From this, I conclude that LibreSSL does not allow disabling TLSv1.3?  This feels like it should be version-gated, not just across the board.

Off the top of my head, I do not understand the ramifications of enabling or not enabling TLSv1.3 (I'm not up to date on which versions are still good and which have been broken).

Can you shed any light on what this particular commit is for, and why it is structured the way it is?

**Comment by anatoli26** [comment]
Ellie,

I agree with your proposed titles for the commits. The author of all of them is Antoine Jacoutot.

The commits from openbsd/ports whose parts are included in this PR are:
* configure.ac: https://github.com/openbsd/ports/commit/7f4aca029a04ffd77f8dcd516e42373c5488e49f#diff-66cc3f61d8de3d14a950d37d06d09ace (2010-12-02)
* imap/tls.c: https://github.com/openbsd/ports/commit/bb5cf32330222eba44bfe54f63ea7b3bca34ab01#diff-c68f1a6b56a2fa4c033c49856391b00e (2019-11-17)
* lib/byteorder64.h: https://github.com/openbsd/ports/commit/864539ed796dc6deec35b389e07b0e7e29a5a230#diff-aa715205b94f99ec4ade42c8ad7d37fa (2015-03-15)
* imap/fud.c: https://github.com/openbsd/ports/commit/f3ba0e3a3ec8cf332633c5a9447a49acfc39ecc3#diff-59e0948461306885d49ffc7a12267790 (2017-05-28)

The commit messages don't provide enough detail to improve on your descriptions. But I could ask Antoine about the details if needed.

With respect to the tls.c `LIBRESSL_VERSION_NUMBER`, I'm not 100% sure, but I understand that the patch checks the presence of LibreSSL (which is a OpenBSD team project) and if we're building with it, we disable the TLS1.3 part as LibreSSL lacked it in the server component until 2 months ago (v3.2.0 was released on 2020-05-31 that enabled it for the 1st time [1]). It's not included in any -RELEASE yet, but it will be in the upcoming 6.8-RELEASE.

I guess we could drop this patch entirely form the OpenBSD port too, as the current version builds on -CURRENT (i.e. it does include the TLS 1.3 in LibreSSL) and when it becomes included in the upcoming -RELEASE it'll be compiled with the LibreSSL supporting TLS 1.3 too.

Please let me know how to proceed. Should I rewrite the commit messages as you suggested, dropping the 2nd patch? The 1st line for each commit would be the texts you specified and in the details it would say:

`Original author: Antoine Jacoutot, openbsd/ports@7f4aca0`

Does it look good?

[1] https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.2.0-relnotes.txt

**Comment by elliefm** [comment]
Yep, that looks good. :)

It would be nice to support LibreSSL, but it sounds like it's a little bit in flux at the moment.  Let's proceed with dropping p2 as planned for now, and let that one remain an OpenBSD-only patch.  

I expect OpenBSD will probably update this patch to handle the difference between old- and new-LibreSSL, in the same way as we already need to handle old- and new- OpenSSL.  So we can reconsider this one patch for upstreaming sometime in the future, but skip it for now

**Comment by anatoli26** [comment]
@elliefm, I just reworded the 3 commits and dropped the LibreSSL one as discussed.

**Comment by anatoli26** [comment]
With respect to LibreSSL, AFAIK the OpenBSD cyrus-imapd port is compiled with LibreSSL, it just had no TLS 1.3 support yet (that's why the 2nd patch). But it'll be ok from now on.

**Comment by anatoli26** [comment]
Hi @elliefm, any update on the PR?

**Comment by elliefm** [comment]
Thanks for the ping, sorry I've been sidetracked debugging some stuff and forgot to come back to this one!

**Comment by elliefm** [comment]
I've also cherry-picked these three commits to the 3.2 branch, so they'll be in 3.2.3 when that comes out

**Comment by felixjogris** [comment]
I tried this on OpenBSD 6.7 amd64 today:
`./configure --enable-idled --enable-http --with-sqlite=/usr/local --with-sasl=/usr/local`
```
# autoreconf -i 
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `cmulocal'.
libtoolize: copying file `cmulocal/libtool.m4'
libtoolize: copying file `cmulocal/ltoptions.m4'
libtoolize: copying file `cmulocal/ltsugar.m4'
libtoolize: copying file `cmulocal/ltversion.m4'
libtoolize: copying file `cmulocal/lt~obsolete.m4'
configure.ac:134: installing './compile'
configure.ac:57: installing './config.guess'
configure.ac:57: installing './config.sub'
configure.ac:81: installing './install-sh'
configure.ac:81: installing './missing'
Makefile.am: installing './depcomp'
configure.ac: installing './ylwrap'
```
gmake stops here:
```
mv -f lib/.deps/lib_libcyrus_la-cyrusdb_quotalegacy.Tpo lib/.deps/lib_libcyrus_la-cyrusdb_quotalegacy.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I/root/2/cyrus-imapd/com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include/libxml2 -I/usr/local/include  -I/usr/local/include  -I/usr/local/include -I/usr/local/include      -I/usr/local/include  -I/usr/local/include   -fvisibility=hidden  -g -O2 -MT lib/lib_libcyrus_la-cyrusdb_skiplist.lo -MD -MP -MF lib/.deps/lib_libcyrus_la-cyrusdb_skiplist.Tpo -c -o lib/lib_libcyrus_la-cyrusdb_skiplist.lo `test -f 'lib/cyrusdb_skiplist.c' || echo './'`lib/cyrusdb_skiplist.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/root/2/cyrus-imapd/com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H -I/usr/local/include -I/usr/local/include -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -fvisibility=hidden -g -O2 -MT lib/lib_libcyrus_la-cyrusdb_skiplist.lo -MD -MP -MF lib/.deps/lib_libcyrus_la-cyrusdb_skiplist.Tpo -c lib/cyrusdb_skiplist.c  -fPIC -DPIC -o lib/.libs/lib_libcyrus_la-cyrusdb_skiplist.o
mv -f lib/.deps/lib_libcyrus_la-cyrusdb_skiplist.Tpo lib/.deps/lib_libcyrus_la-cyrusdb_skiplist.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I/root/2/cyrus-imapd/com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include/libxml2 -I/usr/local/include  -I/usr/local/include  -I/usr/local/include -I/usr/local/include      -I/usr/local/include  -I/usr/local/include   -fvisibility=hidden  -g -O2 -MT lib/lib_libcyrus_la-cyrusdb_twoskip.lo -MD -MP -MF lib/.deps/lib_libcyrus_la-cyrusdb_twoskip.Tpo -c -o lib/lib_libcyrus_la-cyrusdb_twoskip.lo `test -f 'lib/cyrusdb_twoskip.c' || echo './'`lib/cyrusdb_twoskip.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/root/2/cyrus-imapd/com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H -I/usr/local/include -I/usr/local/include -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -fvisibility=hidden -g -O2 -MT lib/lib_libcyrus_la-cyrusdb_twoskip.lo -MD -MP -MF lib/.deps/lib_libcyrus_la-cyrusdb_twoskip.Tpo -c lib/cyrusdb_twoskip.c  -fPIC -DPIC -o lib/.libs/lib_libcyrus_la-cyrusdb_twoskip.o
In file included from lib/cyrusdb_twoskip.c:57:
lib/byteorder.h:56:1: warning: "be16toh" redefined
In file included from /usr/include/sys/types.h:45,
                 from /usr/include/sys/select.h:37,
                 from /usr/include/sys/time.h:38,
                 from ./config.h:663,
                 from lib/cyrusdb_twoskip.c:43:
/usr/include/sys/endian.h:61:1: warning: this is the location of the previous definition
In file included from lib/cyrusdb_twoskip.c:57:
lib/byteorder.h:57:1: warning: "be32toh" redefined
In file included from /usr/include/sys/types.h:45,
                 from /usr/include/sys/select.h:37,
                 from /usr/include/sys/time.h:38,
                 from ./config.h:663,
                 from lib/cyrusdb_twoskip.c:43:
/usr/include/sys/endian.h:62:1: warning: this is the location of the previous definition
In file included from lib/cyrusdb_twoskip.c:57:
lib/byteorder.h:58:1: warning: "be64toh" redefined
In file included from /usr/include/sys/types.h:45,
                 from /usr/include/sys/select.h:37,
                 from /usr/include/sys/time.h:38,
                 from ./config.h:663,
                 from lib/cyrusdb_twoskip.c:43:
/usr/include/sys/endian.h:63:1: warning: this is the location of the previous definition
In file included from lib/cyrusdb_twoskip.c:57:
lib/byteorder.h:69:41: error: missing binary operator before token "("
lib/cyrusdb_twoskip.c:578: warning: 'optimize' attribute directive ignored
lib/cyrusdb_twoskip.c:851: warning: 'optimize' attribute directive ignored
lib/cyrusdb_twoskip.c:876: warning: 'optimize' attribute directive ignored
lib/cyrusdb_twoskip.c:903: warning: 'optimize' attribute directive ignored
gmake[2]: *** [Makefile:5870: lib/lib_libcyrus_la-cyrusdb_twoskip.lo] Error 1
gmake[2]: Leaving directory '/root/2/cyrus-imapd'
gmake[1]: *** [Makefile:6919: all-recursive] Error 1
gmake[1]: Leaving directory '/root/2/cyrus-imapd'
gmake: *** [Makefile:3221: all] Error 2
```

My system's info:
```
obsd# uname -a  
OpenBSD obsd.intra.ogris.net 6.7 GENERIC.MP#182 amd64
obsd# pkg_info                                                                                                                                                                                                                                                                                       
autoconf-2.69p2     automatically configure source code on many Un*x platforms
automake-1.16.2     GNU Standards-compliant Makefile generator
bison-3.3.2p1       GNU parser generator
curl-7.69.1p1       get files from FTP, Gopher, HTTP or HTTPS servers
cvsps-2.1p2         generate patchsets from CVS repositories
cyrus-sasl-2.1.27p1 RFC 2222 SASL (Simple Authentication and Security Layer)
db-4.6.21p7v0       Berkeley DB package, revision 4
gettext-runtime-0.20.1p1 GNU gettext runtime libraries and programs
git-2.26.2p0        distributed version control system
gmake-4.3           GNU make
icu4c-67.1          International Components for Unicode
intel-firmware-20200508v0 microcode update binaries for Intel CPUs
jansson-2.12        library for manipulating JSON data
libical-3.0.8       implementation of the iCalendar protocols and data units
libiconv-1.16p0     character set conversion library
libltdl-2.4.2p1     GNU libtool system independent dlopen wrapper
libsigsegv-2.12     library for handling page faults in user mode
libtool-2.4.2p0     generic shared library support script
libxml-2.9.10p0     XML parsing library
m4-1.4.18p0         GNU m4
metaauto-1.0p3      wrapper for gnu auto*
nghttp2-1.40.0      library for HTTP/2
p5-Error-0.17028    error/exception handling in an OO-ish way
p5-Mail-Tools-2.21  modules for handling mail with perl
p5-Time-TimeDate-2.30 library for parsing and formatting dates and times
quirks-3.326        exceptions to pkg_add rules
sqlite3-3.31.1p0    embedded SQL implementation
vim-8.2.534-no_x11  vi clone, many additional features
vmm-firmware-1.11.0p2 firmware binary images for vmm(4) driver
xz-5.2.5            LZMA compression and decompression tools
```
Vanilla 3.2.3 on OpenBSD stops at this point:
```mv -f imap/.deps/imap_libcyrus_imap_la-idlemsg.Tpo imap/.deps/imap_libcyrus_imap_la-idlemsg.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I/root/cyrus-imapd-3.2.3/com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include/libxml2 -I/usr/local/include  -I/usr/local/include  -I/usr/local/include -I/usr/local/include      -I/usr/local/include  -I/usr/local/include  -DPIC -fPIC   -fvisibility=hidden -g -O2 -MT imap/imap_libcyrus_imap_la-imapparse.lo -MD -MP -MF imap/.deps/imap_libcyrus_imap_la-imapparse.Tpo -c -o imap/imap_libcyrus_imap_la-imapparse.lo `test -f 'imap/imapparse.c' || echo './'`imap/imapparse.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/root/cyrus-imapd-3.2.3/com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H -I/usr/local/include -I/usr/local/include -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -DPIC -fPIC -fvisibility=hidden -g -O2 -MT imap/imap_libcyrus_imap_la-imapparse.lo -MD -MP -MF imap/.deps/imap_libcyrus_imap_la-imapparse.Tpo -c imap/imapparse.c  -fPIC -DPIC -o imap/.libs/imap_libcyrus_imap_la-imapparse.o
imap/imapparse.c:89: warning: 'optimize' attribute directive ignored
mv -f imap/.deps/imap_libcyrus_imap_la-imapparse.Tpo imap/.deps/imap_libcyrus_imap_la-imapparse.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I/root/cyrus-imapd-3.2.3/com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include/libxml2 -I/usr/local/include  -I/usr/local/include  -I/usr/local/include -I/usr/local/include      -I/usr/local/include  -I/usr/local/include  -DPIC -fPIC   -fvisibility=hidden -g -O2 -MT imap/imap_libcyrus_imap_la-index.lo -MD -MP -MF imap/.deps/imap_libcyrus_imap_la-index.Tpo -c -o imap/imap_libcyrus_imap_la-index.lo `test -f 'imap/index.c' || echo './'`imap/index.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/root/cyrus-imapd-3.2.3/com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H -I/usr/local/include -I/usr/local/include -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -DPIC -fPIC -fvisibility=hidden -g -O2 -MT imap/imap_libcyrus_imap_la-index.lo -MD -MP -MF imap/.deps/imap_libcyrus_imap_la-index.Tpo -c imap/index.c  -fPIC -DPIC -o imap/.libs/imap_libcyrus_imap_la-index.o
In file included from imap/jmap_util.h:47,
                 from imap/index.c:74:
/usr/local/include/jansson.h: In function 'json_incref':
/usr/local/include/jansson.h:124: error: '__ATOMIC_ACQUIRE' undeclared (first use in this function)
/usr/local/include/jansson.h:124: error: (Each undeclared identifier is reported only once
/usr/local/include/jansson.h:124: error: for each function it appears in.)
/usr/local/include/jansson.h: In function 'json_decref':
/usr/local/include/jansson.h:134: error: '__ATOMIC_RELEASE' undeclared (first use in this function)
imap/index.c: At top level:
imap/index.c:6408: warning: 'optimize' attribute directive ignored
imap/index.c:6590: warning: 'optimize' attribute directive ignored
imap/index.c:6606: warning: 'optimize' attribute directive ignored
imap/index.c:6622: warning: 'optimize' attribute directive ignored
imap/index.c:6641: warning: 'optimize' attribute directive ignored
imap/index.c:6663: warning: 'optimize' attribute directive ignored
imap/index.c:6685: warning: 'optimize' attribute directive ignored
gmake[2]: *** [Makefile:4987: imap/imap_libcyrus_imap_la-index.lo] Error 1
gmake[2]: Leaving directory '/root/cyrus-imapd-3.2.3'
gmake[1]: *** [Makefile:6561: all-recursive] Error 1
gmake[1]: Leaving directory '/root/cyrus-imapd-3.2.3'
gmake: *** [Makefile:2898: all] Error 2
```
Git without this patch:
```
mv -f lib/.deps/lib_libcyrus_la-cyrusdb_quotalegacy.Tpo lib/.deps/lib_libcyrus_la-cyrusdb_quotalegacy.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I/root/cyrus-imapd/com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include/libxml2 -I/usr/local/include  -I/usr/local/include  -I/usr/local/include -I/usr/local/include      -I/usr/local/include  -I/usr/local/include  -DPIC -fPIC   -fvisibility=hidden  -g -O2 -MT lib/lib_libcyrus_la-cyrusdb_skiplist.lo -MD -MP -MF lib/.deps/lib_libcyrus_la-cyrusdb_skiplist.Tpo -c -o lib/lib_libcyrus_la-cyrusdb_skiplist.lo `test -f 'lib/cyrusdb_skiplist.c' || echo './'`lib/cyrusdb_skiplist.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/root/cyrus-imapd/com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H -I/usr/local/include -I/usr/local/include -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -DPIC -fPIC -fvisibility=hidden -g -O2 -MT lib/lib_libcyrus_la-cyrusdb_skiplist.lo -MD -MP -MF lib/.deps/lib_libcyrus_la-cyrusdb_skiplist.Tpo -c lib/cyrusdb_skiplist.c  -fPIC -DPIC -o lib/.libs/lib_libcyrus_la-cyrusdb_skiplist.o
mv -f lib/.deps/lib_libcyrus_la-cyrusdb_skiplist.Tpo lib/.deps/lib_libcyrus_la-cyrusdb_skiplist.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I/root/cyrus-imapd/com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include/libxml2 -I/usr/local/include  -I/usr/local/include  -I/usr/local/include -I/usr/local/include      -I/usr/local/include  -I/usr/local/include  -DPIC -fPIC   -fvisibility=hidden  -g -O2 -MT lib/lib_libcyrus_la-cyrusdb_twoskip.lo -MD -MP -MF lib/.deps/lib_libcyrus_la-cyrusdb_twoskip.Tpo -c -o lib/lib_libcyrus_la-cyrusdb_twoskip.lo `test -f 'lib/cyrusdb_twoskip.c' || echo './'`lib/cyrusdb_twoskip.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/root/cyrus-imapd/com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H -I/usr/local/include -I/usr/local/include -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -DPIC -fPIC -fvisibility=hidden -g -O2 -MT lib/lib_libcyrus_la-cyrusdb_twoskip.lo -MD -MP -MF lib/.deps/lib_libcyrus_la-cyrusdb_twoskip.Tpo -c lib/cyrusdb_twoskip.c  -fPIC -DPIC -o lib/.libs/lib_libcyrus_la-cyrusdb_twoskip.o
In file included from lib/cyrusdb_twoskip.c:57:
lib/byteorder.h:64:41: error: missing binary operator before token "("
lib/cyrusdb_twoskip.c:578: warning: 'optimize' attribute directive ignored
lib/cyrusdb_twoskip.c:851: warning: 'optimize' attribute directive ignored
lib/cyrusdb_twoskip.c:876: warning: 'optimize' attribute directive ignored
lib/cyrusdb_twoskip.c:903: warning: 'optimize' attribute directive ignored
gmake[2]: *** [Makefile:5870: lib/lib_libcyrus_la-cyrusdb_twoskip.lo] Error 1
gmake[2]: Leaving directory '/root/cyrus-imapd'
gmake[1]: *** [Makefile:6919: all-recursive] Error 1
gmake[1]: Leaving directory '/root/cyrus-imapd'
gmake: *** [Makefile:3221: all] Error 2```

**Comment by anatoli26** [comment]
@felixjogris, I made some comments in the other issue, but one important point when building ports on OpenBSD is to use -current, not -release. There could be a number of changes (especially updated libs) that are not in the -release and that could easily lead to the errors you experience.

Try building cyrus-imapd on -current using the ports infrastructure as I mentioned in the other issue and if you still get errors, post them here.

To switch from -release to -current you can issue: `doas sysupgrade -s`.

**Pull request merged**
