### PR TITLE
imapd.c:base_capabilities — mention PARTIAL - RFC 9394 as not implemented

### PR DESCRIPTION
**Pull request by dilyanpalauzov**

### CODE REVIEW

**Review by elliefm — APPROVED** [review]

**Comment by elliefm** [comment]
@ksmurchison This looks straightforward and fine to me, but is there anything I've missed?

**Comment by ksmurchison** [comment]
This looks fine to me.  We might also want to add RFC 9394 to the rfc-support.html wishlist

**Comment by elliefm** [comment]
I'm not really sure what the criteria for something being on the wishlist is, or to put it another way, what it means for something to be on there.  From a very brief skim of history, it looks like most of the entries in it were added by Jeroen or @dilyanpalauzov... or perhaps they just reformatted the file at some point -- I didn't look deeply.  Anyway, it looks like Dilyan at least knows how to add entries to the wishlist, or did at one time (reminder: it's at the bottom of `docsrc/imap/rfc-support.rst`)

@dilyanpalauzov Do you want to add this one to the wishlist?  I'm happy to just merge this PR as is, but if you want to add it to the wishlist too, please go ahead.  I'll probably merge this early next week if I haven't heard back from you in the meantime.  Thanks! :)

**Comment by ksmurchison** [comment]
Some of what is in the current wishlist looks like it might already be implemented.  I guess I'll audit that list.

**Comment by dilyanpalauzov** [comment]
I do not understand what is the purpose of the wishlist.  Is it to state explicitly, that some RFCs are not supported?  Or is it part of a roadmap, as in the present there are no other forms of roadmap?

**Comment by ksmurchison** [comment]
Superseded by #4662

**Pull request closed without merging**
