### PR TITLE
timsieved, user: fix script path for users with dots in their names

### PR DESCRIPTION
**Pull request by maciejsszmigiero**
For an user "foo.bar" with a sieve directory of /var/spool/sieve lmtp
searches for his scripts in a /var/spool/sieve/f/foo^bar/ directory but
timsieved creates and manages them in a /var/spool/sieve/f/foo.bar/
directory.

This is caused by an inconsistency in an user name -> path translation
between sieve_find_script() in imap/lmtp_sieve.c and actions_setuser() in
timsieved/actions.c.

Fix this by adding dot-translating code from imap/lmtp_sieve.c also to
timsieved/actions.c.

This change will need to be applied to 3.0 branch, too.

### CODE REVIEW

**Comment by maciejsszmigiero** [comment]
Looks like imap/user.c need a similar fix so renaming an user account from or to a name with a dot would work correctly.
Added a commit fixing it to this PR, too.

**Comment by maciejsszmigiero** [comment]
Ping.

**Comment by dilyanpalauzov** [comment]
There are three places,where the path to the sieve directory is computed:
* in imap/lmtp_sieve/sieve_find_script()
* in imap/user.c:user_sieve_path(), and in 
* timsieved/actions.c:action_setuser()

Only the first replaces fullstops with carets, so if timsieved doesn't upload files in carets-directories, but with fullstops, lmtp_sieve will not find them.

The . -> ^ change was added with 69bfaea35 and I don't understand why.

In any case, I propose reducing the three implementations to a single one, without _rm_dots (as currenlty there are no files that lmtp_sieve could find uploaded by timsieved).

I changed the interface of user_sieve_path to return dynamically allocated memory, instead of static one, so that I can use it in multi-threaded code without mutexes.

In imap/autocreate.c:autocreate_sieve IMAPOPT_SIEVEDIR has default value,  so that it cannot be undefined.


```diff
diff --git a/imap/autocreate.c b/imap/autocreate.c
--- a/imap/autocreate.c
+++ b/imap/autocreate.c
@@ -104,7 +104,6 @@ static int autocreate_sieve(const char *userid, const char *source_script)
     int do_compile = 0;
     const char *compiled_source_script = NULL;
     const char *sievename = get_script_name(source_script);
-    const char *sieve_script_dir = NULL;
     char sieve_script_name[MAX_FILENAME];
     char sieve_bcscript_name[MAX_FILENAME];
     char sieve_default[MAX_FILENAME];
@@ -121,18 +120,13 @@ static int autocreate_sieve(const char *userid, const char *source_script)
         return 1;
     }
 
-    /* Check if sievedir is defined in imapd.conf */
-    if(!config_getstring(IMAPOPT_SIEVEDIR)) {
-        syslog(LOG_WARNING, "autocreate_sieve: sievedir option is not defined. Check imapd.conf");
-        return 1;
-    }
-
     /* Check if autocreate_sieve_compiledscript is defined in imapd.conf */
     if(!(compiled_source_script = config_getstring(IMAPOPT_AUTOCREATE_SIEVE_SCRIPT_COMPILED))) {
         syslog(LOG_WARNING, "autocreate_sieve: autocreate_sieve_compiledscript option is not defined. Compiling it");
         do_compile = 1;
     }
 
+    const char *sieve_script_dir;
     if (!(sieve_script_dir = user_sieve_path(userid))) {
         syslog(LOG_WARNING, "autocreate_sieve: unable to determine sieve directory for user %s", userid);
         return 1;
@@ -140,30 +134,37 @@ static int autocreate_sieve(const char *userid, const char *source_script)
 
     if(snprintf(sieve_tmpname, MAX_FILENAME, "%s/%s.script.NEW",sieve_script_dir, sievename) >= MAX_FILENAME) {
         syslog(LOG_WARNING, "autocreate_sieve: Invalid sieve path %s, %s, %s", sieve_script_dir, sievename, userid);
+        free(sieve_script_dir);
         return 1;
     }
     if(snprintf(sieve_bctmpname, MAX_FILENAME, "%s/%s.bc.NEW",sieve_script_dir, sievename) >= MAX_FILENAME) {
         syslog(LOG_WARNING, "autocreate_sieve: Invalid sieve path %s, %s, %s", sieve_script_dir, sievename, userid);
+        free(sieve_script_dir);
         return 1;
     }
     if(snprintf(sieve_script_name, MAX_FILENAME, "%s/%s.script",sieve_script_dir, sievename) >= MAX_FILENAME) {
         syslog(LOG_WARNING, "autocreate_sieve: Invalid sieve path %s, %s, %s", sieve_script_dir, sievename, userid);
+        free(sieve_script_dir);
         return 1;
     }
     if(snprintf(sieve_bcscript_name, MAX_FILENAME, "%s/%s.bc",sieve_script_dir, sievename) >= MAX_FILENAME) {
         syslog(LOG_WARNING, "autocreate_sieve: Invalid sieve path %s, %s, %s", sieve_script_dir, sievename, userid);
+        free(sieve_script_dir);
         return 1;
     }
     if(snprintf(sieve_default, MAX_FILENAME, "%s/%s",sieve_script_dir,"defaultbc") >= MAX_FILENAME) {
         syslog(LOG_WARNING, "autocreate_sieve: Invalid sieve path %s, %s, %s", sieve_script_dir, sievename, userid);
+        free(sieve_script_dir);
         return 1;
     }
     /* XXX no directory? umm */
     if(snprintf(sieve_bclink_name, MAX_FILENAME, "%s.bc", sievename) >= MAX_FILENAME) {
         syslog(LOG_WARNING, "autocreate_sieve: Invalid sieve path %s, %s, %s", sieve_script_dir, sievename, userid);
+        free(sieve_script_dir);
         return 1;
     }
 
+    free(sieve_script_dir);
     /* Check if a default sieve filter alrady exists */
     if(!stat(sieve_default,&statbuf)) {
         syslog(LOG_WARNING,"autocreate_sieve: Default sieve script already exists");
diff --git a/imap/lmtp_sieve.c b/imap/lmtp_sieve.c
--- a/imap/lmtp_sieve.c
+++ b/imap/lmtp_sieve.c
@@ -61,6 +61,7 @@
 #include "duplicate.h"
 #include "exitcodes.h"
 #include "global.h"
+#include "imap/user.h"
 #include "lmtpd.h"
 #include "lmtp_sieve.h"
 #include "lmtpengine.h"
@@ -80,7 +81,6 @@
 #include "imap/lmtpstats.h"
 
 static int sieve_usehomedir = 0;
-static const char *sieve_dir = NULL;
 
 /* data per script */
 typedef struct script_data {
@@ -794,11 +794,6 @@ sieve_interp_t *setup_sieve(void)
         strarray_append(&mark, "\\flagged");
 
     sieve_usehomedir = config_getswitch(IMAPOPT_SIEVEUSEHOMEDIR);
-    if (!sieve_usehomedir) {
-        sieve_dir = config_getstring(IMAPOPT_SIEVEDIR);
-    } else {
-        sieve_dir = NULL;
-    }
 
     interp = sieve_interp_alloc(NULL);
     assert(interp != NULL);
@@ -832,18 +827,9 @@ sieve_interp_t *setup_sieve(void)
     return interp;
 }
 
-static void _rm_dots(char *p)
-{
-    for (; *p; p++) {
-        if (*p == '.') *p = '^';
-    }
-}
-
 static int sieve_find_script(const char *user, const char *domain,
                              const char *script, char *fname, size_t size)
 {
-    char *ext = NULL;
-
     if (!user && !script) {
         return -1;
     }
@@ -862,47 +848,36 @@ static int sieve_find_script(const char *user, const char *domain,
         /* check ~USERNAME/.sieve */
         snprintf(fname, size, "%s/%s", pent->pw_dir, script ? script : ".sieve");
     } else { /* look in sieve_dir */
-        size_t len = strlcpy(fname, sieve_dir, size);
-
-        if (domain) {
-            char dhash = (char) dir_hash_c(domain, config_fulldirhash);
-            len += snprintf(fname+len, size-len, "%s%c/%s",
-                            FNAME_DOMAINDIR, dhash, domain);
-        }
-
-        if (!user) { /* global script */
-            len = strlcat(fname, "/global/", size);
-        }
-        else {
-            char hash = (char) dir_hash_c(user, config_fulldirhash);
-            char *usercopy = xstrdup(user);  // stupid hashing of names, we SHOULD just allow dots on disk
-            _rm_dots(usercopy);
-            len += snprintf(fname+len, size-len, "/%c/%s/", hash, usercopy);
-            free(usercopy);
-
-            if (!script) { /* default script */
-                char *bc_fname;
-
-                strlcat(fname, "defaultbc", size);
-
-                bc_fname = sieve_getdefaultbcfname(fname);
-                if (bc_fname) {
-                    sieve_rebuild(NULL, bc_fname, 0, NULL);
-                    free(bc_fname);
-                }
-
-                return 0;
+        char x[PATH_MAX];
+        char *ext;
+        if (user && domain) {
+            snprintf(x, sizeof(x), "%s@%s", user, domain);
+            ext = user_sieve_path(x);
+        } else if (user)
+            ext = user_sieve_path(user);
+        else if (domain) {
+            snprintf(x, sizeof(x), "@%s", domain);
+            ext = user_sieve_path(x);
+        } else
+            ext = user_sieve_path(NULL);
+
+        size_t len = strlcpy(fname, ext, size);
+        free(ext);
+
+        if (!script) { /* default script */
+            strlcat(fname + len, "/defaultbc", size - len);
+
+            char* bc_fname = sieve_getdefaultbcfname(fname);
+            if (bc_fname) {
+                sieve_rebuild(NULL, bc_fname, 0, NULL);
+                free(bc_fname);
             }
-        }
 
-        snprintf(fname+len, size-len, "%s.bc", script);
-    }
-
-    /* don't do this for ~username ones */
-    ext = strrchr(fname, '.');
-    if (ext && !strcmp(ext, ".bc"))
+            return 0;
+        }
+        snprintf(fname+len, size-len, "/%s.bc", script);
         sieve_rebuild(NULL, fname, 0, NULL);
-
+    }
     return 0;
 }
 
diff --git a/imap/mbdump.c b/imap/mbdump.c
--- a/imap/mbdump.c
+++ b/imap/mbdump.c
@@ -660,7 +660,7 @@ EXPORTED int dump_mailbox(const char *tag, struct mailbox *mailbox, uint32_t uid
          * xxx can't use home directories currently
          * (it makes almost no sense in the conext of a murder) */
         if (!sieve_usehomedir) {
-            const char *sieve_path = user_sieve_path(userid);
+            char *sieve_path = user_sieve_path(userid);
             mbdir = opendir(sieve_path);
 
             if (!mbdir) {
@@ -693,13 +693,17 @@ EXPORTED int dump_mailbox(const char *tag, struct mailbox *mailbox, uint32_t uid
 
                         /* dump file */
                         r = dump_file(0, !tag, pin, pout, filename, tag_fname, NULL, 0);
-                        if (r) goto done;
+                        if (r) {
+                            free(sieve_path);
+                            goto done;
+                        }
                     }
                 }
 
                 closedir(mbdir);
                 mbdir = NULL;
             }
+            free(sieve_path);
         } /* end if !sieve_userhomedir */
 
     } /* end if user INBOX */
@@ -833,7 +837,6 @@ EXPORTED int undump_mailbox(const char *mbname,
     int r = 0;
     int curfile = -1;
     struct mailbox *mailbox = NULL;
-    const char *sieve_path = NULL;
     int sieve_usehomedir = config_getswitch(IMAPOPT_SIEVEUSEHOMEDIR);
     char *userid = NULL;
     int first_annotation = 1;
@@ -857,9 +860,6 @@ EXPORTED int undump_mailbox(const char *mbname,
 
     if (mboxname_isusermailbox(mbname, 1)) {
         userid = mboxname_to_userid(mbname);
-        if(!sieve_usehomedir) {
-            sieve_path = user_sieve_path(userid);
-        }
     }
 
     c = getword(pin, &data);
@@ -1123,9 +1123,11 @@ EXPORTED int undump_mailbox(const char *mbname,
                        realname);
                 continue;
             } else {
+                char *sieve_path = user_sieve_path(userid);
                 if(snprintf(fnamebuf, sizeof(fnamebuf),
                             "%s/%s", sieve_path, realname) == -1) {
                     r = IMAP_PROTOCOL_ERROR;
+                    free(sieve_path);
                     goto done;
                 } else if(isdefault) {
                     char linkbuf[2048];
@@ -1146,6 +1148,7 @@ EXPORTED int undump_mailbox(const char *mbname,
                     }
 
                 }
+                free(sieve_path);
             }
         } else {
             struct data_file *df;
diff --git a/imap/sync_support.c b/imap/sync_support.c
--- a/imap/sync_support.c
+++ b/imap/sync_support.c
@@ -986,7 +986,7 @@ void sync_sieve_list_free(struct sync_sieve_list **lp)
 struct sync_sieve_list *sync_sieve_list_generate(const char *userid)
 {
     struct sync_sieve_list *list = sync_sieve_list_create();
-    const char *sieve_path = user_sieve_path(userid);
+    char *sieve_path = user_sieve_path(userid);
     char filename[2048];
     char active[2048];
     DIR *mbdir;
@@ -1033,6 +1033,7 @@ struct sync_sieve_list *sync_sieve_list_generate(const char *userid)
         free(result);
     }
     closedir(mbdir);
+    free(sieve_path);
 
     if (active[0])
         sync_sieve_list_set_active(list, active);
@@ -1042,7 +1043,7 @@ struct sync_sieve_list *sync_sieve_list_generate(const char *userid)
 
 char *sync_sieve_read(const char *userid, const char *name, uint32_t *sizep)
 {
-    const char *sieve_path = user_sieve_path(userid);
+    char *sieve_path = user_sieve_path(userid);
     char filename[2048];
     FILE *file;
     struct stat sbuf;
@@ -1054,6 +1055,7 @@ char *sync_sieve_read(const char *userid, const char *name, uint32_t *sizep)
         *sizep = 0;
 
     snprintf(filename, sizeof(filename), "%s/%s", sieve_path, name);
+    free(sieve_path);
 
     file = fopen(filename, "r");
     if (!file) return NULL;
@@ -1085,7 +1087,6 @@ int sync_sieve_upload(const char *userid, const char *name,
                       time_t last_update, const char *content,
                       size_t len)
 {
-    const char *sieve_path = user_sieve_path(userid);
     char tmpname[2048];
     char newname[2048];
     char *ext;
@@ -1100,10 +1101,12 @@ int sync_sieve_upload(const char *userid, const char *name,
         return 0;
     }
 
+    char *sieve_path = user_sieve_path(userid);
     if (stat(sieve_path, &sbuf) == -1 && errno == ENOENT) {
         if (cyrus_mkdir(sieve_path, 0755) == -1) return IMAP_IOERROR;
         if (mkdir(sieve_path, 0755) == -1 && errno != EEXIST) {
             syslog(LOG_ERR, "Failed to create %s:%m", sieve_path);
+            free(sieve_path);
             return IMAP_IOERROR;
         }
     }
@@ -1111,6 +1114,7 @@ int sync_sieve_upload(const char *userid, const char *name,
     snprintf(tmpname, sizeof(tmpname), "%s/sync_tmp-%lu",
              sieve_path, (unsigned long)getpid());
     snprintf(newname, sizeof(newname), "%s/%s", sieve_path, name);
+    free(sieve_path);
 
     if ((file=fopen(tmpname, "w")) == NULL) {
         return IMAP_IOERROR;
@@ -1148,7 +1152,7 @@ int sync_sieve_upload(const char *userid, const char *name,
 
 int sync_sieve_activate(const char *userid, const char *name)
 {
-    const char *sieve_path = user_sieve_path(userid);
+    char *sieve_path = user_sieve_path(userid);
     char target[2048];
     char active[2048];
     char tmp[2048];
@@ -1162,6 +1166,7 @@ int sync_sieve_activate(const char *userid, const char *name)
     sieve_rebuild(NULL, bc_fname, 0, NULL);
     free(bc_fname);
 #endif
+    free(sieve_path);
 
     /* N.B symlink() does NOT verify target for anything but string validity,
      * so activation of a nonexistent script will report success.
@@ -1184,11 +1189,12 @@ int sync_sieve_activate(const char *userid, const char *name)
 
 int sync_sieve_deactivate(const char *userid)
 {
-    const char *sieve_path = user_sieve_path(userid);
+    char *sieve_path = user_sieve_path(userid);
     char active[2048];
 
-    snprintf(active, sizeof(active), "%s/%s", sieve_path, "defaultbc");
+    snprintf(active, sizeof(active), "%s/defaultbc", sieve_path);
     unlink(active);
+    free(sieve_path);
 
     sync_log_sieve(userid);
 
@@ -1197,7 +1203,7 @@ int sync_sieve_deactivate(const char *userid)
 
 int sync_sieve_delete(const char *userid, const char *name)
 {
-    const char *sieve_path = user_sieve_path(userid);
+    char *sieve_path = user_sieve_path(userid);
     char filename[2048];
     char active[2048];
     DIR *mbdir;
@@ -1206,8 +1212,10 @@ int sync_sieve_delete(const char *userid, const char *name)
     int is_default = 0;
     int count;
 
-    if (!(mbdir = opendir(sieve_path)))
+    if (!(mbdir = opendir(sieve_path))) {
+        free(sieve_path);
         return(IMAP_IOERROR);
+    }
 
     while((next = readdir(mbdir)) != NULL) {
         if(!strcmp(next->d_name, ".") || !strcmp(next->d_name, ".."))
@@ -1241,6 +1249,7 @@ int sync_sieve_delete(const char *userid, const char *name)
 
     snprintf(filename, sizeof(filename), "%s/%s", sieve_path, name);
     unlink(filename);
+    free(sieve_path);
 
     sync_log_sieve(userid);
 
diff --git a/imap/user.c b/imap/user.c
--- a/imap/user.c
+++ b/imap/user.c
@@ -131,33 +131,57 @@ static int user_deleteacl(char *name, int matchlen, int category, void* rock)
 }
 #endif
 
-EXPORTED const char *user_sieve_path(const char *user)
+/*
+ * Provide user as local@domain. user=NULL for getting the global path for all domains
+ * user=@domain" for the per domain /global, or user=localpart for using the default
+ * domain or with vith virtdomains off. Don't call with terminating '@'.
+ * Free() the result.
+ */
+EXPORTED char *user_sieve_path(const char *user_orig)
 {
-    static char sieve_path[2048];
-    char hash, *domain;
-
-    if (config_virtdomains && (domain = strchr(user, '@'))) {
-        char d = (char) dir_hash_c(domain+1, config_fulldirhash);
-        *domain = '\0';  /* split user@domain */
-        hash = (char) dir_hash_c(user, config_fulldirhash);
-        snprintf(sieve_path, sizeof(sieve_path), "%s%s%c/%s/%c/%s",
-                 config_getstring(IMAPOPT_SIEVEDIR),
-                 FNAME_DOMAINDIR, d, domain+1, hash, user);
-        *domain = '@';  /* reassemble user@domain */
+    char *sieve_path = xmalloc(PATH_MAX), *domain, hash, *user;
+    if (user_orig) {
+        user = strdup(user_orig);
+        if (*user == '@') {
+	    domain = user + 1;
+	    *user = '\0';
+	} else {
+	    if (domain = strchr(user + 1, '@'))
+                *domain++ = '\0';
+            hash = (char) dir_hash_c(user, config_fulldirhash);
+        }
+    } else {
+        domain = NULL;
+        user = strdup("");
     }
-    else {
-        hash = (char) dir_hash_c(user, config_fulldirhash);
-
-        snprintf(sieve_path, sizeof(sieve_path), "%s/%c/%s",
-                 config_getstring(IMAPOPT_SIEVEDIR), hash, user);
+    static const char* config_sieve_path;
+    if (!config_sieve_path) config_sieve_path = config_getstring(IMAPOPT_SIEVEDIR);
+    if (config_virtdomains && domain) {
+        char d = (char) dir_hash_c(domain, config_fulldirhash);
+	if (*user)
+            snprintf(sieve_path, PATH_MAX, "%s%s%c/%s/%c/%s",
+                config_sieve_path,
+                FNAME_DOMAINDIR, d, domain, hash, user);
+	else
+            snprintf(sieve_path, PATH_MAX, "%s%s%c/%s/global",
+                config_sieve_path,
+                FNAME_DOMAINDIR, d, domain);
+    } else {
+        if (*user)
+            snprintf(sieve_path, PATH_MAX, "%s/%c/%s",
+                config_sieve_path, hash, user);
+	else
+            snprintf(sieve_path, PATH_MAX, "%s/global",
+                config_sieve_path, hash);
     }
 
+    free(user);
+
     return sieve_path;
 }
 
 static int user_deletesieve(const char *user)
 {
-    const char *sieve_path;
     char filename[2048];
     DIR *mbdir;
     struct dirent *next = NULL;
@@ -165,7 +189,7 @@ static int user_deletesieve(const char *user)
     /* oh well */
     if(config_getswitch(IMAPOPT_SIEVEUSEHOMEDIR)) return 0;
 
-    sieve_path = user_sieve_path(user);
+    char *sieve_path = user_sieve_path(user);
 
     mbdir = opendir(sieve_path);
 
@@ -185,7 +209,7 @@ static int user_deletesieve(const char *user)
         /* remove mbdir */
         rmdir(sieve_path);
     }
-
+    free(sieve_path);
     return 0;
 }
 
@@ -276,50 +300,15 @@ static int user_renamesub(const char *name, void* rock)
 
 static int user_renamesieve(const char *olduser, const char *newuser)
 {
-    char hash, *domain;
-    char oldpath[2048], newpath[2048];
-    int r;
-
     /* oh well */
     if(config_getswitch(IMAPOPT_SIEVEUSEHOMEDIR)) return 0;
-
-    if (config_virtdomains && (domain = strchr(olduser, '@'))) {
-        char d = (char) dir_hash_c(domain+1, config_fulldirhash);
-        *domain = '\0';  /* split user@domain */
-        hash = (char) dir_hash_c(olduser, config_fulldirhash);
-        snprintf(oldpath, sizeof(oldpath), "%s%s%c/%s/%c/%s",
-                 config_getstring(IMAPOPT_SIEVEDIR),
-                 FNAME_DOMAINDIR, d, domain+1, hash, olduser);
-        *domain = '@';  /* reassemble user@domain */
-    }
-    else {
-        hash = (char) dir_hash_c(olduser, config_fulldirhash);
-
-        snprintf(oldpath, sizeof(oldpath), "%s/%c/%s",
-                 config_getstring(IMAPOPT_SIEVEDIR), hash, olduser);
-    }
-
-    if (config_virtdomains && (domain = strchr(newuser, '@'))) {
-        char d = (char) dir_hash_c(domain+1, config_fulldirhash);
-        *domain = '\0';  /* split user@domain */
-        hash = (char) dir_hash_c(newuser, config_fulldirhash);
-        snprintf(newpath, sizeof(newpath), "%s%s%c/%s/%c/%s",
-                 config_getstring(IMAPOPT_SIEVEDIR),
-                 FNAME_DOMAINDIR, d, domain+1, hash, newuser);
-        *domain = '@';  /* reassemble user@domain */
-    }
-    else {
-        hash = (char) dir_hash_c(newuser, config_fulldirhash);
-
-        snprintf(newpath, sizeof(newpath), "%s/%c/%s",
-                 config_getstring(IMAPOPT_SIEVEDIR), hash, newuser);
-    }
-
+    char *oldpath = user_sieve_path(olduser);
+    char *newpath = user_sieve_path(newuser);
     /* rename sieve directory
      *
      * XXX this doesn't rename sieve scripts
      */
-    r = rename(oldpath, newpath);
+    int r = rename(oldpath, newpath);
     if (r < 0) {
         if (errno == ENOENT) {
             syslog(LOG_WARNING, "error renaming %s to %s: %m",
@@ -336,6 +325,8 @@ static int user_renamesieve(const char *olduser, const char *newuser)
             syslog(LOG_ERR, "error renaming %s to %s: %m", oldpath, newpath);
         }
     }
+    free(oldpath);
+    free(newpath);
 
     return r;
 }
diff --git a/imap/user.h b/imap/user.h
--- a/imap/user.h
+++ b/imap/user.h
@@ -46,7 +46,7 @@
 #include "auth.h"
 
 /* path to user's sieve directory */
-const char *user_sieve_path(const char *user);
+char *user_sieve_path(const char *user);
 
 /* Delete meta-data (seen state, subscriptions, ACLs, quotaroots,
  * sieve scripts) for 'user'.
diff --git a/timsieved/actions.c b/timsieved/actions.c
--- a/timsieved/actions.c
+++ b/timsieved/actions.c
@@ -65,6 +65,7 @@
 #include "imap/global.h"
 #include "imap/sync_log.h"
 #include "imap/tls.h"
+#include "imap/user.h"
 #include "imap/version.h"
 #include "sieve/sieve_interface.h"
 #include "timsieved/actions.h"
@@ -76,62 +77,21 @@
 extern int sieved_userisadmin;
 extern sieve_interp_t *interp;
 
-static char *sieve_dir_config = NULL;
-
 static const char *sieved_userid = NULL;
 
-int actions_init(void)
-{
-  int sieve_usehomedir = 0;
-
-  sieve_usehomedir = config_getswitch(IMAPOPT_SIEVEUSEHOMEDIR);
-
-  if (!sieve_usehomedir) {
-      sieve_dir_config = (char *) config_getstring(IMAPOPT_SIEVEDIR);
-  } else {
-      /* can't use home directories with timsieved */
-      syslog(LOG_ERR, "can't use home directories");
-
-      return TIMSIEVE_FAIL;
-  }
-
-  return TIMSIEVE_OK;
-}
-
 int actions_setuser(const char *userid)
 {
-  char userbuf[1024], *user, *domain = NULL;
-  size_t size = 1024, len;
-  int result;
-
-  char *sieve_dir = (char *) xzmalloc(size+1);
-
-  sieved_userid = xstrdup(userid);
-  user = (char *) userid;
-  if (config_virtdomains && strchr(user, '@')) {
-      /* split the user and domain */
-      strlcpy(userbuf, userid, sizeof(userbuf));
-      user = userbuf;
-      if ((domain = strrchr(user, '@'))) *domain++ = '\0';
-  }
-
-  len = strlcpy(sieve_dir, sieve_dir_config, size);
-
-  if (domain) {
-      char dhash = (char) dir_hash_c(domain, config_fulldirhash);
-      len += snprintf(sieve_dir+len, size-len, "%s%c/%s",
-                      FNAME_DOMAINDIR, dhash, domain);
-  }
-
+  char *sieve_dir;
   if (sieved_userisadmin) {
-      strlcat(sieve_dir, "/global", size);
-  }
-  else {
-      char hash = (char) dir_hash_c(user, config_fulldirhash);
-      snprintf(sieve_dir+len, size-len, "/%c/%s", hash, user);
-  }
-
-  result = chdir(sieve_dir);
+      char *domain = strchr(userid, '@');
+      if (domain) {
+          char x[2048];
+          snprintf(x, sizeof(x), "@%s", domain);
+          sieve_dir = user_sieve_path(x);
+      } else sieve_dir = user_sieve_path(NULL);
+  } else sieve_dir = user_sieve_path(userid);
+
+  int result = chdir(sieve_dir);
   if (result != 0) {
       result = cyrus_mkdir(sieve_dir, 0755);
       if (!result) result = mkdir(sieve_dir, 0755);
diff --git a/timsieved/actions.h b/timsieved/actions.h
--- a/timsieved/actions.h
+++ b/timsieved/actions.h
@@ -111,13 +111,6 @@ int listscripts(struct protstream *conn);
 
 int setactive(struct protstream *conn, const struct buf *name);
 
-/*
- * Initialize
- *
- */
-
-int actions_init(void);
-
 /*
  * Set user after sucessful authentication
  *
diff --git a/timsieved/timsieved.c b/timsieved/timsieved.c
--- a/timsieved/timsieved.c
+++ b/timsieved/timsieved.c
@@ -280,8 +280,11 @@ EXPORTED int service_main(int argc __attribute__((unused)),
     secprops = mysasl_secprops(0);
     sasl_setprop(sieved_saslconn, SASL_SEC_PROPS, secprops);
 
-    if (actions_init() != TIMSIEVE_OK)
-      fatal("Error initializing actions",-1);
+    if (config_getswitch(IMAPOPT_SIEVEUSEHOMEDIR)) {
+        /* can't use home directories with timsieved */
+        syslog(LOG_ERR, "can't use home directories");
+        fatal("Error initializing actions",-1);
+    }
 
     sieved_tls_required = config_getswitch(IMAPOPT_TLS_REQUIRED);
 

```

**Comment by maciejsszmigiero** [comment]
> The . -> ^ change was added with 69bfaea and I don't understand why.

Probably for consistency with lock subdirectories, spool subdirectories and quota files, all of which
have a '^' character where a dot would have been.
Removing this mangling rule would break existing installations.

Note that this is also a problem in stable 3.0-branch releases.

**Comment by ksmurchison** [comment]
I like the idea of reducing the path creation into a single function.  I'm wondering if we couldn't also use the mbname_*() apis

**Comment by maciejsszmigiero** [comment]
> I like the idea of reducing the path creation into a single function

This is a minimalny-invasive change to fix a bug in cyrus-imapd, a bug that is present in both master and 3.0 branches.

There is no reason why the code couldn't be refactored later in the master branch.

**Comment by dilyanpalauzov** [comment]
On master with 73af8e19546f235f6286cc9147a3ea74bde19ebb the inconsistency in `imap/lmtp_sieve.c:sieve_find_script()` was solved.  Preparing the pull request might have been lost time.

**Comment by maciejsszmigiero** [comment]
> On master with 73af8e1 the inconsistency in imap/lmtp_sieve.c:sieve_find_script() was solved. 
> Preparing the pull request might have been lost time.

That change was only commited 3 days ago, while this pull request was opened over half a year ago.

Also:
1) The change in master is not backwards-compatible since Sieve scripts on existing setups are going
to be searched for in a wrong place, so upgrade notes should remind people to move them,

2) Since it is a bug we need to fix stable 3.0 branch, too, and there the fixes shouldn't change the
imap directory layout.

That's why this PR is still relevant.

**Comment by elliefm** [comment]
> That change was only commited 3 days ago, while this pull request was opened over half a year ago.

Sorry about that.  I went on extended leave a few days before you submitted this PR, and I guess it slipped through the cracks once I returned.

The fix in 73af8e1 is the correct, minimal stable fix.  `lmtpd` only ever reads script files, it does not write them, and this fix corrects `lmtpd` to read them from the disk location where they're actually written (i.e. the path with dots).  This fix is also on the cyrus-imapd-3.0 branch and will be in the next release.

>Probably for consistency with lock subdirectories, spool subdirectories and quota files, all of which
have a '^' character where a dot would have been.

Longer term, I believe it would be desirable to change the sieve script path to use the same mangling behaviour as those do, but this will mean sieve data migrations for people upgrading.  So it'll want a solid, single implementation (probably in `user_sieve_path()`?) with tests and an upgrade path.

**Comment by dilyanpalauzov** [comment]
In short term consolidating the five places where sieve script' paths are calculated to a single function, without performing any migration, is a very good idea.

**Comment by maciejsszmigiero** [comment]
Since you implemented a different solution on both branches I will now close this pull request.

> lmtpd only ever reads script files, it does not write them, and this fix corrects lmtpd to read them
> from the disk location where they're actually written (i.e. the path with dots). 
> This fix is also on the cyrus-imapd-3.0 branch and will be in the next release.

I still think upgrade notes should at least mention this change so Sieve scripts don't suddenly stop
working for people that put them into directories where lmtpd used to search for them.
This is not a fully backward-compatible change.

**Comment by elliefm** [comment]
> I still think upgrade notes should at least mention this change so Sieve scripts don't suddenly stop
working for people that put them into directories where lmtpd used to search for them.
This is not a fully backward-compatible change.

This is a really good point, thanks.  I'll make sure the release notes for the next release mention this detail.

**Pull request closed without merging**
