### PR TITLE
Revert "IMAP QUOTA (RFC 9208) Implementation"

### PR DESCRIPTION
**Pull request by elliefm**
Reverts cyrusimap/cyrus-imapd#4379

### CODE REVIEW

**Comment by elliefm** [comment]
approved via slack by @brong, who can't click the actual approve button at the moment for unrelated reasons

**Comment by elliefm** [comment]
Actually I'm gonna hold my horses on this one, until we work out how to safely navigate that MAILBOX_MINOR_VERSION bump, because reverting will wind it back, but it can't go backwards.

**Comment by elliefm** [comment]
The good news is the revert passes CI, at least.

**Review by brong — APPROVED** [review]
This looks good, thanks for doing it.  We'll try again later :)

**Pull request merged**
