### PR TITLE
Prepare for Cyrus-SASL 2.1.28

### PR DESCRIPTION
**Pull request by quanah**
Signed-off-by: Quanah Gibson-Mount <quanah@symas.com>

### CODE REVIEW

**Review by elliefm — APPROVED** [review]

**Comment by elliefm** [comment]
Do we have an anticipated release date, or just "when it's ready"?

This PR should theoretically be merged around the time it's actually released, so the /dev website update is synchronised... but I'll also need to cherry-pick the commit to the stable branch so the main website gets it too, which introduces a delay, since we're in different timezones and I'm only available three days a week.

So maybe we should plan to merge and cherry-pick it a little earlier than the actual release, and the website will be ahead of reality for a bit?  The alternative is that the release happens, but the main website lags behind a day or two.  I'm not really sure which is preferable, but I guess either is okay with me.  Do you have a preference?

Also, do you get a "Merge pull request" button?

**Comment by elliefm** [comment]
I've backported this to the 2.5, 3.0, 3.2, 3.4, and 3.6 branches.  The website changes should take affect a little after the next hour... will check later and make sure it looks okay.

**Comment by quanah** [comment]
Awesome, thanks @elliefm !

**Comment by elliefm** [comment]
Looks like it's worked okay, https://www.cyrusimap.org now says (near the bottom):

> The latest stable version of Cyrus SASL is 2.1.28.

As do the /2.5, /3.0, /3.2, /3.4, /3.6, and /dev versions of the site.

**Pull request merged**
