### PR TITLE
Correct values set, but unused

### PR DESCRIPTION
**Pull request by bogdro**
Should fix most of:
- https://github.com/cyrusimap/cyrus-imapd/issues/2213
- https://github.com/cyrusimap/cyrus-imapd/issues/2212

I chose not to correct quota.c:errmsg(), because it looks like an easy copy-paste pattern to allow adding new if-conditions in the future.

I chose to comment-out the assignments in case someone would add some default values again in the future, causing the same warnings. You are free to delete the commented-out code instead.

### CODE REVIEW

**Review by elliefm — CHANGES_REQUESTED** [review]
Thanks! Sorry for the late review.

There's no need to leave old code lying around in comments, so please just remove it if you're removing it.  If we want it back later, it's in the git history.

This no longer merges cleanly.  If you're still around, can you rebase on current master to fix the conflicts and then force push please?

**Comment by bogdro** [comment]
Hi!
Yes, I'm still around. I'll try to do all that when I have a bit of time.

**Comment by elliefm** [comment]
Something has gone wrong with your rebase.  The only commits on the PR should be yours.  Probably your local master branch is not up to date with the upstream master branch, and you have rebased against your local one rather than the upstream one; or you have merged a master branch into your PR branch, instead of rebasing the PR branch onto the master branch.

You should first get your local master branch to the same point as the upstream one, and then rebase your PR branch onto that.  If you have not made changes on your own master branch, then you can update it something like below, assuming your git remote for this repository is called "upstream" (run `git remote -vv` to see the names).

**n.b. If you _have_ made changes on your local master branch, they will be lost if you proceed!**

```
# switch to your local master branch
git checkout master
# update your refs from the "upstream" remote
git fetch upstream
# force the local master to match the one on "upstream"
git reset --hard upstream/master
# your local master will now match the upstream master
# switch to your PR branch
git checkout codeqa
# redo the rebase against the local master
git rebase master
# visually confirm that the only new commits are now your ones
git log upstream/master..HEAD
# and then test and push your PR branch however you usually do
git push
```

**Comment by bogdro** [comment]
Thanks for the help.
I did that, looked correct, but pushing failed due to the remote branch being forward.
After syncing all with master and attempting another rebase, I got conflicts during the rebase, again on the same files, but also brand-new conflicts, and quite many of those (don't know why, since everything should be synced).
To make it easier, can we close this PR and use https://github.com/cyrusimap/cyrus-imapd/pull/5131 instead?

**Pull request closed without merging**
