### PR TITLE
imapd.c: fix proxying UID Search (issue #5047)

### PR DESCRIPTION
**Pull request by ksmurchison**
I think this is a much simpler fix than #5138.  If approved, we should close #5138 #5139 #5140

### CODE REVIEW

**Comment by elliefm** [comment]
The fix does look simple.  I guess this was able to be broken because we didn't have any tests for it, so we should add a test now so we don't break it again.

If I understand the problem correctly, it might be enough to add a UID search to the existing MurderIMAP.frontend_commands test.  Or perhaps add a regular search to MurderIMAP.frontend_commands, and then make a duplicate frontend_commands_uid test that does all the same things but with UID.  I think you can do this by passing `UsingUID=>1` or something like that to the `get_client()` call at the start of the test.

**Comment by ksmurchison** [comment]
@elliefm Yeah, good call.  I will add tests tomorrow

**Review by elliefm — APPROVED** [review]
Nice test, thanks!

**Comment by elliefm** [comment]
Turns out this didn't need to be backported to 3.6 after all, the bug it fixes was introduced with multisearch, which 3.6 doesn't have.  I backported the test though, which passes.

**Pull request merged**
