### PR TITLE
http_dav.c: can't multiget from a non-mailbox (e.g., /dav/addressbooks/)

### PR DESCRIPTION
**Pull request by ksmurchison**
Fixes a crasher for a DAV:multiget request for /dav/addressbooks

### CODE REVIEW

**Review by rsto — APPROVED** [review]
LGTM

**Comment by wolfsage** [comment]
Would this be hard to add tests for?

**Comment by ksmurchison** [comment]
Nope.  Will add one now

**Comment by wolfsage** [comment]
Thanks, much appreciated

**Pull request merged**
